import type { Metadata } from "next";
import { AlertTriangle, CheckCircle2, LockKeyhole } from "lucide-react";
import { FactoryHeader } from "@/components/factory-header";

export const metadata: Metadata = { title: "Production standards", description: "Website Factory verification and delivery standards." };

const deliverables = ["Independent preview URL", "Complete website source", "Every-page website PDF", "Logo and favicon files", "Myndy avatar brief and agent context", "Lead-form test result", "Customer email and SMS drafts", "Signed-off approval checklist", "Unverified and missing information list"];
const checks = ["All navigation and page routes", "Phone, email, and CTA links", "Mobile, tablet, and desktop layouts", "Keyboard use, labels, focus, and contrast", "Form validation, consent, spam, success, and error states", "Spelling, visible draft labels, and image relevance", "SEO, social metadata, schema, and favicon", "Privacy copy and third-party service disclosure"];

export default function StandardsPage() {
  return <main className="min-h-screen bg-[#f5f6f8]"><FactoryHeader /><section className="mx-auto max-w-6xl px-5 py-12 sm:px-8 lg:py-16"><p className="text-sm font-black uppercase tracking-[.16em] text-[#bd1e2c]">Release gate</p><h1 className="mt-3 max-w-4xl text-5xl font-black leading-[.95] tracking-[-.04em] sm:text-7xl">Nothing ships on assumption.</h1><div className="mt-12 grid gap-5 lg:grid-cols-3"><article className="bg-[#101828] p-7 text-white"><LockKeyhole className="text-red-300" /><h2 className="mt-8 text-2xl font-black">Form activation</h2><p className="mt-3 leading-7 text-slate-300">A verified recipient email and a successful controlled submission are both required. A configured key alone is not approval.</p></article><article className="border border-amber-300 bg-amber-50 p-7"><AlertTriangle className="text-amber-700" /><h2 className="mt-8 text-2xl font-black">Claims policy</h2><p className="mt-3 leading-7 text-amber-950">Addresses, reviews, certifications, prices, guarantees, history, and service areas require a recorded source. Otherwise omit or label as draft.</p></article><article className="border border-slate-300 bg-white p-7"><CheckCircle2 className="text-emerald-700" /><h2 className="mt-8 text-2xl font-black">Customer approval</h2><p className="mt-3 leading-7 text-slate-600">Approval identifies the reviewer, date, resolved exceptions, deployment target, form result, and final content state.</p></article></div><div className="mt-12 grid gap-10 lg:grid-cols-2"><section><p className="text-xs font-black uppercase tracking-[.16em] text-slate-500">Required package / 09</p><h2 className="mt-2 text-3xl font-black">Customer deliverables</h2><ol className="mt-6 divide-y divide-slate-300 border-y border-slate-300">{deliverables.map((item,index)=><li key={item} className="flex gap-5 bg-white px-4 py-4"><span className="font-black text-[#bd1e2c]">{String(index+1).padStart(2,"0")}</span><span className="font-bold">{item}</span></li>)}</ol></section><section><p className="text-xs font-black uppercase tracking-[.16em] text-slate-500">Preflight / 08</p><h2 className="mt-2 text-3xl font-black">Verification coverage</h2><ul className="mt-6 grid gap-3">{checks.map(item=><li key={item} className="flex gap-3 border border-slate-300 bg-white p-4"><CheckCircle2 className="shrink-0 text-[#bd1e2c]" size={20} /><span>{item}</span></li>)}</ul></section></div></section></main>;
}
