import Link from "next/link";
import { DesignGrid } from "./design-grid";
import { V2Shell } from "../shell";

const journey = [
  ["01", "Request", "Share your business, audience, goals, and creative direction."],
  ["02", "Review", "We review the requirements and agree on a focused brief."],
  ["03", "Preview", "Explore a responsive concept built around your business."],
  ["04", "Approval", "Check the details and request changes before approval."],
  ["05", "Delivery", "Receive a clear handoff after the required reviews."],
];

export function V2Home() {
  return <V2Shell><div className="v2-container"><section className="v2-hero"><span className="v2-badge">● WEBSITE STUDIO FOR RED SPECTRUM CLIENTS</span><h1>Explore customer websites with <em>RS WebFactory.</em></h1><p>A thoughtful workflow for collecting requests, reviewing existing customer previews, and preparing the next chapter online.</p><div className="v2-actions"><Link className="v2-button v2-red" href="/request">Start a website request ↗</Link><Link className="v2-button v2-quiet" href="/designs#customer-previews">Browse customer previews</Link></div><div className="v2-trust"><span>Existing customer previews</span><span>Customer privacy first</span><span>A clear path to launch</span></div><div className="v2-workbench"><header><b>● ● ● &nbsp; RS Studio Workbench</b><span>Illustrative workflow</span></header><div className="v2-workbench-grid">{[["Website request", "Share your goals", 22], ["Design preview", "Review the direction", 65], ["Final approval", "Confirm before delivery", 90]].map(([title, subtitle, progress]) => <article key={title}><span className="v2-badge">Sample stage</span><h3>{title}</h3><p>{subtitle}</p><div className="v2-mini-progress"><i style={{ width: `${progress}%` }} /></div><small className="v2-muted">No customer records shown</small></article>)}</div></div></section></div><div className="v2-tint"><section className="v2-container v2-section"><div className="v2-section-head"><div><span className="v2-eyebrow">Predictable production</span><h2>The 5-step website journey</h2></div><p className="v2-muted">From first request to careful handoff.</p></div><div className="v2-journey">{journey.map(([number, title, description]) => <article key={number}><b>{number}</b><h3>{title}</h3><p>{description}</p></article>)}</div></section></div><section className="v2-container v2-section"><div className="v2-section-head"><div><span className="v2-eyebrow">A little inspiration</span><h2>Find your next online identity.</h2></div><Link href="/designs">Explore all designs ↗</Link></div><DesignGrid /><div className="v2-actions v2-preview-link"><Link className="v2-button v2-quiet" href="/designs#customer-previews">See existing customer websites ↗</Link></div></section><section className="v2-privacy-band"><h2>Private customer data stays private.</h2><p>Public design previews show creative directions. Contact details, internal notes, and review logs remain protected.</p><div className="v2-trust"><span>No public customer contact data</span><span>Manual review checkpoints</span><span>Separate admin access</span></div></section><section className="v2-container v2-section v2-section-head"><div><span className="v2-eyebrow">Let’s build what’s next</span><h2>Your business deserves a better first impression.</h2><p className="v2-muted">Tell us what you have in mind. We’ll help shape the direction.</p></div><Link href="/request" className="v2-button v2-red">Start your request ↗</Link></section></V2Shell>;
}
