import Link from "next/link";
import { ClientShell, V2Intro } from "../shell";

type ClientSection = "overview" | "projects" | "messages" | "files" | "profile";

const pages: Record<ClientSection, { title: string; description: string }> = {
  overview: { title: "Your website workspace", description: "A preview of the future client experience. Secure customer accounts are not connected yet." },
  projects: { title: "Projects", description: "Explore a sample project layout. Real customer projects require verified account ownership." },
  messages: { title: "Messages", description: "Project messaging will appear after secure customer authentication and delivery controls are connected." },
  files: { title: "Files & delivery", description: "Private uploads and package downloads are unavailable until authorized storage is connected." },
  profile: { title: "Your profile", description: "Profile editing requires a secure, verified customer account." },
};

export function ClientSectionPage({ section }: { section: ClientSection }) {
  const page = pages[section];
  return <ClientShell><V2Intro eyebrow="Client experience · sample only" title={page.title} description={page.description} /><section className="v2-container v2-section" style={{ paddingTop: 0 }}>
    {(section === "overview" || section === "projects") && <div className="v2-two"><div className="v2-card"><span className="v2-badge">Sample project</span><h2 style={{ margin: "15px 0" }}>Your next website</h2><p className="v2-muted">A sample walkthrough of the review journey. No customer account or private project data is loaded.</p><div className="v2-mini-progress"><i style={{ width: "55%" }} /></div><p className="v2-muted">Request → Review → Brief → Preview → Approval → Delivery</p><Link className="v2-button v2-red" href="/client/projects/sample-project">Explore sample project ↗</Link></div><div className="v2-card"><h3>What happens next?</h3><p className="v2-muted">Start with the real request form. The team reviews your details and prepares a protected preview. Client login and approval are pending secure account support.</p><Link href="/request" className="v2-button v2-quiet">Start a real request ↗</Link></div></div>}
    {section === "messages" && <div className="v2-two"><div className="v2-card"><div className="v2-section-head"><h2>Project conversation</h2><span className="v2-badge">Not connected</span></div><div className="v2-empty">No messages can be loaded without a verified customer session.</div><label className="v2-disabled-field">Your message<textarea disabled placeholder="Messaging becomes available after secure account access is connected." /></label><button className="v2-button" disabled>Send message unavailable</button></div><aside className="v2-card"><h3>Conversation privacy</h3><p className="v2-muted">Only a verified project owner should see messages and staff responses. This sample view contains no real conversation history.</p></aside></div>}
    {section === "files" && <div className="v2-two"><div className="v2-card"><div className="v2-section-head"><h2>Project files</h2><span className="v2-badge">Private storage pending</span></div><div className="v2-file-list"><div><strong>File</strong><strong>Availability</strong></div><div><span>Brand assets</span><span>Unavailable</span></div><div><span>Website handoff</span><span>Unavailable</span></div></div><p className="v2-muted">Uploads and downloads require secure storage and verified ownership. No sample text file is presented as a real package.</p><button className="v2-button" disabled>Upload unavailable</button></div><aside className="v2-card"><h3>Handoff stages</h3><ol><li>Confirm the reviewed preview</li><li>Complete QA and approval</li><li>Prepare a private delivery manifest</li></ol><Link className="v2-button v2-quiet" href="/client/delivery/sample-project">View sample delivery ↗</Link></aside></div>}
    {section === "profile" && <div className="v2-two"><div className="v2-card"><h2>Account connection pending</h2><p className="v2-muted">Name, company and contact details are not shown or edited without verified customer sign-in.</p><div className="v2-disabled-field"><label>Display name<input disabled placeholder="Available after sign-in" /></label><label>Company<input disabled placeholder="Available after sign-in" /></label><label>Email address<input disabled placeholder="Available after verification" /></label></div><button className="v2-button" disabled>Save profile unavailable</button></div><aside className="v2-card"><h3>Protected account</h3><p className="v2-muted">A future customer session must enforce ownership for project details, profile changes, messages and delivery files.</p></aside></div>}
  </section></ClientShell>;
}
