import Image from 'next/image';
import type { CSSProperties } from 'react';
import type { CustomerSite,CustomerPage } from '@/lib/customers/schema';
import type { SiteDesign } from '@/lib/customers/design-contract';
import './generated-site.css';
import {UniqueHomeB2B} from './unique-home-b2b';
const titles={home:'Home',services:'Capabilities',about:'About',contact:'Contact',privacy:'Privacy'};
export function GeneratedSite({site,page}:{site:CustomerSite;page:CustomerPage}){
 if(site.slug==='unique-home-enterprise'&&site.design?.version==='3.0')return <UniqueHomeB2B site={site} page={page}/>;
 const d=site.design!;const root='/'+site.slug;const images=[site.images.hero,...site.images.gallery];
 const photo=(index:number,priority=false)=>{const p=images[index%images.length];return <Image src={p.src} alt={p.alt} width={p.width} height={p.height} sizes="(max-width: 700px) 100vw, (max-width: 1100px) 70vw, 1400px" priority={priority}/>;};
 const contact=<a className="gs-button" href={root+'/contact'}>Start a conversation <span aria-hidden>↗</span></a>;
 const section=(s:SiteDesign['pages']['home'][number],i:number)=><section key={i} className={`gs-section gs-${s.kind} ${s.reverse?'gs-reverse':''}`}><div className="gs-copy"><p className="gs-kicker">{s.eyebrow}</p><h2>{s.heading}</h2><p>{s.body}</p>{s.kind==='contact'?contact:s.kind==='steps'?<ol><li><span>01</span>Contact</li><li><span>02</span>Discuss your needs</li><li><span>03</span>Confirm next steps</li></ol>:null}</div>{['split','image','columns'].includes(s.kind)&&<figure>{photo(s.image)}<figcaption>Illustrative imagery · not a company project</figcaption></figure>}</section>;
 return <div className={`generated-site gs-${d.typography} gs-${d.spacing} gs-nav-${d.navigation}`} style={{'--gs-ink':site.branding.secondary,'--gs-accent':site.branding.accent,'--gs-paper':site.branding.surface} as CSSProperties}>
 <a className="gs-skip" href="#main">Skip to content</a><div className="gs-preview">Design preview · business details subject to final review</div>
 <header className="gs-header"><a className="gs-brand" href={root} aria-label={site.business.name+' home'}><Image src={site.branding.logoPath} alt={site.business.name} width={310} height={88} priority/></a><nav aria-label="Main navigation">{Object.entries(titles).filter(([k])=>k!=='privacy').map(([k,v])=><a key={k} href={root+(k==='home'?'':'/'+k)} aria-current={page===k?'page':undefined}>{v}</a>)}</nav><a className="gs-header-cta" href={root+'/contact'}>Get in touch ↗</a><details><summary>Menu <span aria-hidden>☰</span></summary><nav aria-label="Mobile navigation">{Object.entries(titles).map(([k,v])=><a key={k} href={root+(k==='home'?'':'/'+k)}>{v}</a>)}</nav></details></header>
 <main id="main">{page==='home'?<section className={`gs-hero gs-hero-${d.hero}`}><div className="gs-hero-copy"><p className="gs-kicker">{site.pages.home.eyebrow}</p><h1>{site.pages.home.headline}</h1><p>{site.pages.home.intro}</p>{contact}<a className="gs-text-link" href={root+'/about'}>Meet {site.business.name.replace(/ LLC$/,'')} →</a></div><figure>{photo(0,true)}<figcaption>Spaces that inspire conversation. Illustrative photography.</figcaption></figure><div className="gs-hero-index">01 / A considered beginning</div></section>:<section className="gs-page-heading"><p className="gs-kicker">{site.business.name} / {titles[page]}</p><h1>{site.pages[page].headline}</h1><p>{page==='services'?site.pages.services.intro:page==='contact'?site.pages.contact.intro:page==='privacy'?'Draft notice · business and legal review required':site.business.summary}</p></section>}
 {(page==='home'?d.pages[page].slice(1):d.pages[page]).map(section)}
 {page==='contact'&&<section className="gs-contact-details"><div><p className="gs-kicker">Direct contact</p><h2>Let’s begin with<br/>your questions.</h2>{site.contact.person?.value&&<p>{site.contact.person.value}</p>}{site.contact.phone.value&&<a href={'tel:'+site.contact.phone.value.replace(/[^+\d]/g,'')}>{site.contact.phone.value}</a>}{site.contact.email.value&&<a href={'mailto:'+site.contact.email.value}>{site.contact.email.value}</a>}<address>{site.contact.address.value}</address><p>Customer-provided contact details. No office hours or service area are implied.</p></div><div className="gs-inquiry"><h2>Tell us what you have in mind.</h2><p>This preview form is inactive. Nothing entered here is submitted. Use the direct contact details instead.</p><fieldset disabled><label>Name<input autoComplete="off"/></label><label>Email<input type="email" autoComplete="off"/></label><label>Phone<input type="tel" autoComplete="off"/></label><label>Your inquiry<textarea rows={4}/></label><button type="button">Inquiry delivery not enabled</button></fieldset><a href={root+'/privacy'}>Read the draft privacy notice</a></div></section>}
 {page==='privacy'&&<article className="gs-privacy">{site.pages.privacy.body.map((p,i)=><p key={i}>{p}</p>)}</article>}
 </main><footer className="gs-footer"><div><Image src={`/customers/${site.slug}/logo-dark.svg`} alt={site.business.name} width={310} height={88}/><p>{site.business.summary}</p></div><nav aria-label="Footer">{Object.entries(titles).map(([k,v])=><a key={k} href={root+(k==='home'?'':'/'+k)}>{v}</a>)}</nav><div className="gs-footer-bottom"><span>© 2026 {site.business.name}.</span><span>Website designed by <a href="https://www.theredspectrum.com/">Red Spectrum</a>.</span><span>Preview only · Illustrative imagery</span></div></footer></div>;
}
