export const broomSlug = "broom-home-enterprises-llc";

export const broomServices = [
  { slug: "rentals", name: "Rental Properties", verb: "Find your next chapter.", image: "rental", alt: "People carrying moving boxes into a home", intro: "A rental should fit the way you live. Start with your priorities, then ask the right questions about the space, the terms and your next step.", benefits: ["Clarify your preferred property type and timing", "Discuss the features that matter to your daily life", "Understand what to ask before moving forward"], guidance: "Tell us what you are looking for and when you hope to move. Availability, application requirements and lease terms must be confirmed for each property. This website does not advertise available listings." },
  { slug: "buying", name: "Buying", verb: "A place for what comes next.", image: "interior", alt: "A family home with a landscaped front garden", intro: "Buying begins with a clear picture of what matters to you. Bring your questions, your priorities and your vision for the property you want to call your own.", benefits: ["Define your needs and property preferences", "Organize questions for a considered search", "Discuss the steps between interest and a decision"], guidance: "Share your intended use, preferred property type and general timeframe. Financing, inspections, legal review and transaction terms require the appropriate independent professionals. No property availability or outcome is guaranteed." },
  { slug: "selling", name: "Selling", verb: "Prepare for a thoughtful move.", image: "building", alt: "A carefully arranged residential interior", intro: "A considered sale starts well before a property changes hands. Discuss your objectives, the information you have and the preparation your next move may require.", benefits: ["Talk through your reasons and timing for selling", "Identify preparation questions and relevant information", "Establish clear expectations for the next conversation"], guidance: "Start with a general description of the property and your goals. Specific valuations, marketing arrangements, representation and sale terms must be agreed directly. Do not upload deeds or confidential documents through an initial inquiry." },
  { slug: "building", name: "Building", verb: "Give your vision a foundation.", image: "development", alt: "An architectural building exterior", intro: "From an early idea to a more defined direction, a building conversation starts with purpose. Explore the property questions behind the space you want to create.", benefits: ["Describe the intended use and project vision", "Discuss the property considerations behind your idea", "Identify questions to take to qualified specialists"], guidance: "Share your concept and whether you have a site in mind. Feasibility, design, permits, construction services and timelines require separate confirmation with licensed professionals. This website does not promise construction or permitting services." },
  { slug: "holding", name: "Holding", verb: "Think beyond the next move.", image: "hero", alt: "An aerial view of a residential neighborhood", intro: "Property ownership is a continuing commitment. Take a longer view of your objectives, changing needs and the questions that come with holding real estate over time.", benefits: ["Clarify your longer-term ownership objectives", "Consider practical responsibilities and future plans", "Discuss how a property fits your broader priorities"], guidance: "Begin with the type of property and the ownership questions you want to explore. Broom Home does not promise returns or appreciation. For tax, legal or investment advice, consult an appropriately qualified independent adviser." },
] as const;

export function broomService(slug?: string) { return broomServices.find(service => service.slug === slug); }
export function validBroomRoute(route: string[] = []) {
  return route.length === 0 || (route.length === 1 && ["services", "about", "contact", "faq", "privacy"].includes(route[0])) || (route.length === 2 && route[0] === "services" && Boolean(broomService(route[1])));
}

export const broomFaqs = [
  ["Where should I start?", "Call (347) 666-3929 or email info@broomhome.biz. Tell us whether you want to rent, buy, sell, build or discuss holding a property, along with your general priorities and timing."],
  ["Are the properties pictured available?", "The photographs illustrate different aspects of real estate. They are not Broom Home listings or evidence of property ownership. Ask the team directly about current availability and service coverage."],
  ["What should I share about a rental search?", "Start with your preferred property type, features and move-in timeframe. Application requirements and lease terms vary by property and need individual confirmation."],
  ["Can I discuss buying and selling together?", "Yes. Explain both sides of your planned move so the team can understand your priorities. Representation, scope and timing are confirmed directly."],
  ["Can I bring an early-stage building idea?", "Yes. A general description of the intended space and use is a useful starting point. Feasibility, permits, design and construction arrangements require separate review by the appropriate professionals."],
  ["What does holding mean?", "Holding means retaining property over time rather than planning an immediate sale. A conversation can help clarify ownership goals and practical questions. Property values and returns are not guaranteed."],
  ["Can I book an appointment or use live chat here?", "Please call or email to arrange a conversation. This preview has no active appointment booking or live chat. A website visit does not reserve a time."],
  ["What information should I avoid sending?", "Keep the first inquiry general. Do not send bank details, payment information, government identifiers or confidential financial documents. Ask the team about an appropriate process if more information is needed."],
] as const;
