export const umgServices = [
  { slug: 'administrative-management', name: 'Administrative Management', group: 'Business & Operations', image: 3, overview: 'Bring structure to the everyday work that keeps a business moving: administration, coordination, information, and follow-through.', problems: ['Responsibilities that are unclear or duplicated', 'Routine requests that stall between people', 'Administrative work competing with business priorities'], context: 'For an owner or operational decision-maker, better administration starts with understanding how work actually moves. The conversation can cover handoffs, recurring tasks, and the information people need to act.', approach: ['Map recurring work and the people involved.', 'Identify unclear handoffs and practical constraints.', 'Discuss responsibilities and a manageable set of next steps.'] },
  { slug: 'reorganizational-consulting', name: 'Reorganizational Consulting', group: 'Consulting & Strategy', image: 4, overview: 'Look at the way an organization is structured and discuss changes that fit its current priorities, people, and operating needs.', problems: ['A structure that no longer reflects the work', 'Overlapping responsibilities during change', 'Unclear priorities as the business develops'], context: 'Change can affect reporting lines, routines, and the way a business presents itself to its market. A consulting perspective helps frame the questions before decisions are made.', approach: ['Listen to the reasons for change.', 'Review the current structure and points of friction.', 'Compare practical options and discuss a phased direction.'] },
  { slug: 'site-location-consulting', name: 'Site Location Consulting', group: 'Consulting & Strategy', image: 5, overview: 'Consider an office or facility location in relation to the business it needs to support, rather than viewing the address in isolation.', problems: ['Unclear criteria for a future workspace', 'A location that complicates everyday operations', 'Competing priorities around access, space, and business visibility'], context: 'A location decision connects operations with market-facing presence. Discuss how staff, visitors, space requirements, and the surrounding business environment inform the choice.', approach: ['Define the operational purpose of the location.', 'Review requirements and location considerations.', 'Organize the trade-offs for a better-informed discussion.'] },
  { slug: 'business-management', name: 'Business Management', group: 'Business & Operations', image: 6, overview: 'Take a connected view of business structure, priorities, and performance so everyday management supports the wider direction.', problems: ['Day-to-day demands obscuring strategic priorities', 'Business communication that lacks a clear direction', 'Decisions made without a shared view of the situation'], context: 'Business strategy and business visibility are connected. Management conversations can examine how operations, communication, and market-facing presentation support the same priorities, without assuming a particular marketing channel or campaign.', approach: ['Clarify the business priorities and current position.', 'Review how structure and routines support those priorities.', 'Discuss a focused management direction and next steps.'] },
  { slug: 'general-management', name: 'General Management', group: 'Business & Operations', image: 7, overview: 'A broad consulting perspective for organizational, operational, and leadership questions that do not fit neatly into one function.', problems: ['Issues spanning several parts of the organization', 'Competing operational priorities', 'Leadership decisions needing more context'], context: 'Owners, entrepreneurs, and organizations often need a place to start rather than a preselected solution. General management brings the connected parts of the situation into one conversation.', approach: ['Listen to the situation across functions.', 'Separate immediate concerns from wider questions.', 'Agree on an appropriate scope for further work.'] },
  { slug: 'records-management', name: 'Records Management', group: 'Business & Operations', image: 8, overview: 'Discuss a more organized approach to business records and information, with attention to access, consistency, security, and applicable requirements.', problems: ['Information that is difficult to locate', 'Inconsistent record-handling routines', 'Unclear responsibility for maintaining records'], context: 'Records support everyday decisions as well as continuity. Start with the types of information the business uses and the people responsible for it. Any specific legal or compliance requirements need appropriate professional review.', approach: ['Understand the records and workflows in use.', 'Review organization, access, and handling responsibilities.', 'Discuss practical improvements and questions requiring specialist input.'] },
  { slug: 'real-estate-management', name: 'Real Estate Management', group: 'Real Estate Management', image: 9, overview: 'A management perspective on property oversight, including rental operations, maintenance coordination, tenant relations, and property performance.', problems: ['Property responsibilities that need better coordination', 'Maintenance and communication priorities competing for attention', 'Owners needing a clearer view of ongoing operations'], context: 'Real estate is one part of a wider management picture. Begin with the property, the people involved, and the support required. Specific responsibilities and service scope are discussed before an engagement.', approach: ['Understand the property and current responsibilities.', 'Review operational and communication priorities.', 'Discuss an appropriate management scope and next steps.'] },
] as const;

export const umgGroups = ['Business & Operations', 'Consulting & Strategy', 'Real Estate Management'] as const;
export function umgService(slug: string) { return umgServices.find(service => service.slug === slug); }
export function validUmgRoute(segments: string[] = []) {
  return segments.length === 0 || (segments.length === 1 && ['services', 'about', 'contact', 'privacy', 'thank-you'].includes(segments[0])) || (segments.length === 2 && segments[0] === 'services' && Boolean(umgService(segments[1])));
}
