import Link from 'next/link';
import { ClientShell, V2Intro } from '@/components/webfactory/v2/shell';
import { currentCustomerSession, getCustomerProject } from '@/lib/webfactory/project-data';
export const metadata = { title: 'Customer Payment & Review', robots: { index: false, follow: false } };
export const dynamic = 'force-dynamic';
export default async function Page() {
  let project = null, unavailable = false;
  try { if (await currentCustomerSession()) project = await getCustomerProject('current'); } catch { unavailable = true; }
  return <ClientShell><V2Intro eyebrow="Payment & review" title="Review before checkout." description="Payment stays unavailable until identity, scope and amount are approved through a separate process." /><section className="v2-container v2-section" style={{ paddingTop: 0 }}><div className="v2-two"><article className="v2-card"><span className="v2-badge">Manual review required</span><h2 style={{ margin: '15px 0' }}>{project?.title || 'Project not connected'}</h2>{unavailable ? <p role="status">Request storage is temporarily unavailable.</p> : project ? <><p>Current stage: {project.stageLabel}</p><p>Scope: pending explicit review. Your request details are not a final scope agreement.</p><Link className="v2-button v2-quiet" href="/client/projects/current">Review project status ↗</Link></> : <p>Use the browser where you submitted your request to see its status. A name or email alone cannot verify ownership.</p>}<div className="v2-status-grid"><p><strong>Identity</strong><br/>Verification required</p><p><strong>Eligibility</strong><br/>Manual review required</p><p><strong>Amount due</strong><br/>Pending</p></div><label className="v2-disabled-field"><input type="checkbox" disabled /> Scope acknowledgment unavailable until an approved scope exists.</label><button className="v2-button v2-red" disabled>Checkout unavailable</button><p className="v2-muted">No card information is collected and no charge or recovery is performed.</p></article><aside className="v2-card"><h3>Payment method</h3><p className="v2-muted">Future payment options will appear only after verified identity, an approved scope, an amount due and separately authorized payment activation.</p><div className="v2-notice">No payment method is active.</div></aside></div></section></ClientShell>;
}
