import Image from "next/image";
import { ArrowDown, ArrowRight, ArrowUpRight, Mail, Phone } from "lucide-react";
import type { CustomerSite } from "@/lib/customers/schema";
import { broomFaqs, broomService, broomServices } from "@/lib/customers/broom-content";
import { CustomerMyndy } from "@/components/customers/customer-myndy";
import { BroomInquiryForm } from "./broom-inquiry-form";
import "./broom.css";

type Props = { site: CustomerSite; route?: string[]; root?: string; origin?: string };
const previewRoot = "/broom-home-enterprises-llc";
const assets = "/customers/broom-home-enterprises-llc";
const navigation = [["Home", ""], ["Services", "/services"], ["About", "/about"], ["FAQ", "/faq"]] as const;

function Photo({ name, alt, priority = false, className = "" }: { name: string; alt: string; priority?: boolean; className?: string }) {
  return <div className={`bh-photo ${className}`}><Image src={`${assets}/images/${name}.webp`} alt={`${alt}; illustrative stock photography, not a Broom Home listing.`} fill sizes="(max-width: 600px) 88vw, (max-width: 1440px) 45vw, 720px" priority={priority} /></div>;
}
function Cta({ root, children = "Talk to Our Team", href = "/contact", light = false }: { root: string; children?: React.ReactNode; href?: string; light?: boolean }) {
  return <a className={`bh-button ${light ? "bh-button-light" : ""}`} href={root + href}>{children}<ArrowUpRight size={18} aria-hidden="true" /></a>;
}
function Faq({ compact = false }: { compact?: boolean }) {
  return <div className="bh-faq">{(compact ? broomFaqs.slice(0, 4) : broomFaqs).map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div>;
}
function Process() {
  return <section className="bh-section bh-process"><div className="bh-heading"><p className="bh-kicker">A clear way forward</p><h2>Big decisions.<br /><em>Considered steps.</em></h2></div><ol>{[["Start with a conversation", "Tell us where you are today and what you would like to do next."], ["Bring the picture into focus", "Discuss priorities, questions and the kind of support you need."], ["Agree on the next step", "Confirm the scope, responsibilities and timing directly with the team."]].map(([title, body], i) => <li key={title}><span className="bh-number">0{i + 1}</span><h3>{title}</h3><p>{body}</p></li>)}</ol></section>;
}
function ContactBanner({ root }: { root: string }) {
  return <section className="bh-contact-banner"><div><p className="bh-kicker">Your next chapter</p><h2>Let’s make room<br />for <em>what’s next.</em></h2></div><div><p>One conversation can bring your next move into focus. Tell us what you have in mind.</p><Cta root={root} light /></div></section>;
}
function ServiceCards({ root }: { root: string }) {
  return <div className="bh-service-grid">{broomServices.map((service, i) => <a className="bh-service-card" href={`${root}/services/${service.slug}`} key={service.slug}><span className="bh-number">0{i + 1}</span><h3>{service.name}</h3><p>{service.verb}</p><ArrowUpRight size={22} aria-hidden="true" /></a>)}</div>;
}
function Home({ root }: { root: string }) {
  return <>
    <section className="bh-hero"><div className="bh-hero-copy"><p className="bh-kicker">A considered approach to real estate</p><h1><span className="bh-hero-line">Move With</span><em className="bh-hero-emphasis">Confidence.</em></h1><p className="bh-lead">Real estate guidance for every move—from renting and buying to selling, building and holding.</p><div className="bh-actions"><Cta root={root} href="/services">Explore Our Services</Cta><a className="bh-text-link" href={`${root}/contact`}>Talk to Our Team <ArrowRight size={17} aria-hidden="true" /></a></div><a href="#perspective" className="bh-scroll"><ArrowDown size={16} aria-hidden="true" /> A new perspective starts here</a></div><div className="bh-hero-visual"><Photo name="interior" alt="A two-story family home with a landscaped front garden" priority /><div className="bh-image-note"><span>Spaces for living.<br />Perspective for life.</span><span>01 / BROOM HOME</span></div></div></section>
    <div className="bh-service-ribbon" aria-label="Our service areas">{broomServices.map(s => <a key={s.slug} href={`${root}/services/${s.slug}`}>{s.name}<span aria-hidden="true">↗</span></a>)}</div>
    <section id="perspective" className="bh-section bh-intro"><p className="bh-kicker">Welcome to Broom Home</p><div><h2>More than a property.<br /><em>A move that matters.</em></h2><div className="bh-intro-body"><p>A home, a fresh start, a long-term plan. Every real estate decision has a bigger story behind it. We begin by understanding yours.</p><p>Broom Home Enterprises LLC brings a professional, relationship-first approach to renting, buying, selling, building and holding. Clear conversations. Thoughtful guidance. Your priorities at the center.</p></div><a className="bh-text-link" href={`${root}/about`}>Get to know Broom Home <ArrowRight size={17} aria-hidden="true" /></a></div></section>
    <section className="bh-section bh-perspectives" aria-label="Illustrative real estate perspectives"><div className="bh-heading-row"><div><p className="bh-kicker">A sense of possibility</p><h2>Different spaces.<br /><em>Personal possibilities.</em></h2></div><p>A home, a fresh outlook, a longer-term plan. Your priorities guide the conversation.</p></div><div className="bh-perspective-grid">{[{ image: "architecture", alt: "A timber-clad home beside leafy trees", label: "A place to belong." }, { image: "home", alt: "An urban rooftop terrace and surrounding buildings", label: "Room for possibility." }, { image: "city", alt: "An aerial view of a residential complex", label: "A wider perspective." }].map(item => <figure key={item.image}><Photo name={item.image} alt={item.alt} /><figcaption>{item.label}</figcaption></figure>)}</div><p className="bh-photo-disclaimer">Illustrative photography. These images are not Broom Home listings.</p></section>
    <section className="bh-section bh-services"><div className="bh-heading-row"><div><p className="bh-kicker">Five ways to move forward</p><h2>Wherever you are.<br /><em>Whatever comes next.</em></h2></div><p>Explore a service, find your starting point, and let’s talk about the details.</p></div><ServiceCards root={root} /></section>
    <section className="bh-split bh-section"><Photo name="building" alt="A light-filled bedroom and sitting area" /><div><p className="bh-kicker">The Broom Home approach</p><h2>Grounded in trust.<br /><em>Built around you.</em></h2><p>Real estate can bring unfamiliar questions. Our commitment is to listen carefully, communicate clearly and approach each conversation with integrity.</p><div className="bh-values">{[["Clarity", "Understand the questions before deciding on the next step."], ["Care", "Your needs and priorities shape the conversation."], ["Perspective", "Consider today’s decision alongside tomorrow’s plans."]].map(([title, body]) => <div key={title}><h3>{title}</h3><p>{body}</p></div>)}</div></div></section>
    <section className="bh-longview"><Photo name="hero" alt="Aerial view of a residential neighborhood" /><div><p className="bh-kicker">Building & long-term ownership</p><h2>A vision for today.<br /><em>A view to tomorrow.</em></h2><p>Some plans begin with a blank page. Others grow with the property you already hold. Bring your longer-term questions into a thoughtful conversation.</p><div className="bh-actions"><Cta root={root} href="/services/building" light>Explore Building</Cta><a className="bh-text-link" href={`${root}/services/holding`}>Discover Holding <ArrowRight size={17} aria-hidden="true" /></a></div></div></section>
    <Process />
    <section className="bh-section bh-faq-section"><div><p className="bh-kicker">A little clarity</p><h2>Good questions.<br /><em>A better starting point.</em></h2><a className="bh-text-link" href={`${root}/faq`}>All frequently asked questions <ArrowRight size={17} aria-hidden="true" /></a></div><Faq compact /></section>
    <ContactBanner root={root} />
  </>;
}
function Services({ root }: { root: string }) {
  return <><section className="bh-page-head bh-section"><p className="bh-kicker">Our services</p><h1>Every move has<br /><em>a starting point.</em></h1><p className="bh-lead">Five areas of real estate. One commitment to understanding what matters to you.</p></section><div className="bh-section bh-service-stories">{broomServices.map((service, i) => <article className="bh-split" key={service.slug}><Photo name={service.image} alt={service.alt} /><div><p className="bh-kicker">0{i + 1} / {service.name}</p><h2>{service.verb}</h2><p>{service.intro}</p><ul className="bh-benefits">{service.benefits.map(benefit => <li key={benefit}>{benefit}</li>)}</ul><Cta root={root} href={`/services/${service.slug}`}>Explore {service.name}</Cta></div></article>)}</div><ContactBanner root={root} /></>;
}
function ServiceDetail({ slug, root }: { slug: string; root: string }) {
  const service = broomService(slug)!;
  return <><section className="bh-section bh-detail-hero"><div><a className="bh-text-link" href={`${root}/services`}>← All services</a><p className="bh-kicker">{service.name}</p><h1>{service.verb}</h1><p className="bh-lead">{service.intro}</p><Cta root={root}>Discuss {service.name}</Cta></div><Photo name={service.image} alt={service.alt} priority /></section><section className="bh-section bh-split bh-detail-copy"><div><p className="bh-kicker">Start with what matters</p><h2>A clearer conversation.<br /><em>A considered next step.</em></h2></div><div><ul className="bh-benefits">{service.benefits.map(benefit => <li key={benefit}>{benefit}</li>)}</ul><p>{service.guidance}</p><p>Call <a href="tel:+13476663929">(347) 666-3929</a> or email <a href="mailto:info@broomhome.biz">info@broomhome.biz</a> to begin.</p></div></section><Process /><ContactBanner root={root} /></>;
}
function About({ root }: { root: string }) {
  return <><section className="bh-section bh-page-head"><p className="bh-kicker">About Broom Home</p><h1>Property is personal.<br /><em>So is our approach.</em></h1><p className="bh-lead">Professional guidance begins with a simple commitment: understand the person behind the next move.</p></section><section className="bh-section bh-split"><Photo name="architecture" alt="A timber-clad home beside leafy trees" priority /><div><p className="bh-kicker">Our mission</p><h2>Real estate.<br /><em>Real relationships.</em></h2><p>Broom Home Enterprises LLC is dedicated to real estate service shaped around the diverse needs of its clients. Whether you are exploring a rental, planning to buy or sell, considering a build or thinking about long-term ownership, we welcome the conversation.</p><p>Our approach is grounded in integrity, professionalism and clear communication. We aim to make the next step easier to understand and build relationships that extend beyond a single decision.</p><p>Contact Aminul Haque to discuss your priorities and the support you are looking for.</p><Cta root={root} /></div></section><Process /><ContactBanner root={root} /></>;
}
function Contact({ site, root }: { site: CustomerSite; root: string }) {
  return <><section className="bh-section bh-page-head"><p className="bh-kicker">Let’s talk</p><h1>Tell us about<br /><em>your next move.</em></h1><p className="bh-lead">A question, an early idea or a more defined plan. We’re ready to start the conversation.</p></section><section className="bh-section bh-contact-grid"><aside><Photo name="city" alt="An aerial view of a residential complex" className="bh-contact-photo" /><h2>Connect with<br /><em>Broom Home.</em></h2><p>Contact Aminul Haque</p><a className="bh-contact-link" href="tel:+13476663929"><Phone size={20} aria-hidden="true" /><span><small>Call us</small>(347) 666-3929</span></a><a className="bh-contact-link" href="mailto:info@broomhome.biz"><Mail size={20} aria-hidden="true" /><span><small>Email us</small>info@broomhome.biz</span></a><div id="chat" className="bh-chat-note"><h3>Broom Home Guide</h3><p>{site.myndy.embed.enabled ? "Use the chat button to start a conversation. Please do not share sensitive financial information." : "Live chat is not available on this preview. Please call or email the team for help choosing the right service."}</p></div></aside><BroomInquiryForm root={root} enabled={site.form.mode !== "disabled" && site.form.recipientConfirmed && process.env.WEBFACTORY_BROOM_CONTACT_ENABLED === "true" && (site.form.mode === "test" ? process.env.WEBFACTORY_INTERNAL_NOTIFICATIONS_ENABLED === "true" : site.form.testPassed)} /></section></>;
}

export function BroomWebsite({ site, route = [], root = previewRoot, origin = "https://preview.redspectrum.ai" }: Props) {
  const page = route[0] || "home";
  const schema = { "@context": "https://schema.org", "@type": "Organization", name: site.business.name, "@id": `${origin}${root}/#organization`, url: `${origin}${root || "/"}`, telephone: "+13476663929", email: "info@broomhome.biz", logo: `${origin}${assets}/logo.svg`, description: site.business.summary };
  const service = page === "services" ? broomService(route[1]) : undefined;
  const structuredData = service ? [schema, { "@context": "https://schema.org", "@type": "Service", name: service.name, description: service.intro, url: `${origin}${root}/services/${service.slug}`, provider: { "@id": schema["@id"] } }] : schema;
  return <div className="bh" data-customer-slug={site.slug}><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replaceAll("<", "\\u003c") }} /><a className="bh-skip" href="#bh-main">Skip to content</a><div className="bh-preview">Broom Home Enterprises LLC <span>Website preview</span></div><header className="bh-header"><a href={root || "/"} aria-label="Broom Home Enterprises LLC home"><Image src={`${assets}/logo.svg`} alt="Broom Home Enterprises LLC" width={270} height={58} priority /></a><nav className="bh-desktop-nav" aria-label="Main navigation">{navigation.map(([label, path]) => <a key={label} aria-current={(path === "" ? page === "home" : page === path.slice(1)) ? "page" : undefined} href={(root + path) || "/"}>{label}</a>)}</nav><a className="bh-header-cta" href={`${root}/contact`}>Let’s Talk <ArrowUpRight size={17} aria-hidden="true" /></a><details className="bh-mobile-menu"><summary>Menu <span aria-hidden="true">☰</span></summary><nav aria-label="Mobile navigation">{[...navigation, ["Contact", "/contact"]].map(([label, path]) => <a key={label} aria-current={(path === "" ? page === "home" : page === path.slice(1)) ? "page" : undefined} href={(root + path) || "/"}>{label}</a>)}</nav></details></header>
    <main id="bh-main">{page === "home" ? <Home root={root} /> : page === "services" ? (route[1] ? <ServiceDetail root={root} slug={route[1]} /> : <Services root={root} />) : page === "about" ? <About root={root} /> : page === "contact" ? <Contact root={root} site={site} /> : page === "faq" ? <><section className="bh-section bh-page-head"><p className="bh-kicker">Frequently asked questions</p><h1>A little clarity.<br /><em>A confident start.</em></h1><p className="bh-lead">General guidance to help you prepare for a conversation.</p></section><section className="bh-section bh-faq-page"><Faq /></section><ContactBanner root={root} /></> : <section className="bh-section bh-privacy"><p className="bh-kicker">Privacy notice · Preview</p><h1>Respect for<br /><em>your information.</em></h1>{site.pages.privacy.body.map((p, i) => <section key={p}><h2>{["About this notice", "Inquiry form", "Direct communications", "Live chat", "Technical information", "Photography"][i]}</h2><p>{p}</p></section>)}<Cta root={root} /></section>}</main>
    <footer className="bh-footer"><div className="bh-footer-top"><div><a className="bh-footer-logo" href={root || "/"} aria-label="Broom Home Enterprises LLC home"><Image src={`${assets}/logo-dark.svg`} alt="Broom Home Enterprises LLC" width={290} height={62} /></a><p>Real estate guidance.<br />A longer-term perspective.</p></div><nav aria-label="Footer navigation"><h2>Explore</h2>{[...navigation.slice(1), ["Contact", "/contact"], ["Privacy", "/privacy"]].map(([label, path]) => <a key={label} href={(root + path) || "/"}>{label}</a>)}</nav><div><h2>Start a conversation</h2><a href="tel:+13476663929">(347) 666-3929</a><a href="mailto:info@broomhome.biz">info@broomhome.biz</a><a href={`${root}/contact#chat`}>Broom Home Guide {site.myndy.embed.enabled ? "↗" : "· Chat unavailable"}</a></div></div><div className="bh-footer-bottom"><p>© {new Date().getFullYear()} Broom Home Enterprises LLC</p><p>Photography is illustrative. No pictured property is offered as a listing.</p></div></footer>
    <script src={`${assets}/motion.js`} defer />
    {site.myndy.embed.enabled && <CustomerMyndy agentId={site.myndy.embed.agentId} accent={site.branding.primary} label="Open Broom Home Guide" />}
  </div>;
}
