import Image from "next/image";
import Link from "next/link";
import { ArrowRight, MapPin, Phone, Mail, Truck, Route, Package } from "lucide-react";
import type { CustomerPage, CustomerSite } from "@/lib/customers/schema";
import { CustomerContactForm } from "@/components/customer-contact-form";
import { CustomerMyndy } from "./customer-myndy";
import "./jm.css";

const root = "/jm-trucking";
const topics = [
  [Truck, "01", "Trucking inquiries", "Have freight to move? Share the pickup, destination, and timing so we can discuss your requirements."],
  [Route, "02", "Logistics conversations", "Talk through the details of your shipment, from locations and access to any special considerations."],
  [Package, "03", "Freight quote requests", "Send shipment details to start a quote conversation. Availability and pricing are confirmed directly."],
] as const;
function Nav({ page }: { page: CustomerPage }) { const links = (["home","about","services","contact"] as const); return <><div className="jm-top"><div><span><MapPin/> Birmingham, Alabama</span><a href="tel:+12057718234"><Phone/> Let’s talk freight <b>(205) 771-8234</b></a></div></div><header className="jm-header"><div><Link href={root}><Image src="/customers/jm-trucking/brand/logo-dark.svg" alt="J&M Trucking Logistics LLC" width={260} height={66} priority /></Link><nav>{links.map(item=><Link key={item} href={root+(item==="home"?"":"/"+item)} aria-current={page===item?"page":undefined}>{item[0].toUpperCase()+item.slice(1)}</Link>)}</nav><Link className="jm-quote" href={root+"/contact"}>Request a Quote <ArrowRight/></Link><details className="jm-mobile-menu"><summary aria-label="Open navigation">Menu</summary><nav>{links.map(item=><Link key={item} href={root+(item==="home"?"":"/"+item)}>{item[0].toUpperCase()+item.slice(1)}</Link>)}<Link href={root+"/privacy"}>Privacy</Link></nav></details></div></header></> }
function Cards(){return <div className="jm-cards">{topics.map(([Icon,num,title,text])=><article key={title}><div><Icon/><span>{num}</span></div><h3>{title}</h3><p>{text}</p><Link href={root+"/contact"}>Let’s talk <ArrowRight/></Link></article>)}</div>}
function CTA(){return <section className="jm-cta"><div><div><p>LET’S GET THE CONVERSATION MOVING</p><h2>What’s your next shipment?</h2><span>Tell us about your freight. We’ll take it from there.</span></div><Link className="jm-quote" href={root+"/contact"}>Request a Quote <ArrowRight/></Link></div></section>}
function Home({site}:{site:CustomerSite}){return <><section className="jm-hero"><Image src={site.images.hero.src} alt={site.images.hero.alt} fill priority sizes="100vw"/><div className="jm-shade"/><div className="jm-hero-inner"><p><i/> TRUCKING &amp; LOGISTICS · BIRMINGHAM, ALABAMA</p><h1>Your freight.<br/><em>Our focus.</em></h1><span>{site.pages.home.intro}</span><div><Link className="jm-quote" href={root+"/contact"}>Request a Quote <ArrowRight/></Link><a className="jm-call" href="tel:+12057718234"><Phone/>Call Us</a></div><footer><small>● &nbsp; BASED IN BIRMINGHAM, ALABAMA</small><a href="#intro">DISCOVER J&amp;M ↓</a></footer></div></section><section className="jm-strip"><div><span><MapPin/>Alabama roots<b>Birmingham, Alabama</b></span><span><Phone/>A direct connection<b>Let’s talk about your freight</b></span><span><Route/>Your shipment starts here<b>Tell us where it needs to go</b></span></div></section><section id="intro" className="jm-section jm-two"><div><p>ROOTED IN ALABAMA. FOCUSED ON YOU.</p><h2>A direct connection.<br/>A clear next step.</h2></div><div><b>Based in Birmingham, Alabama, J&amp;M Trucking Logistics LLC is your point of contact for trucking and logistics inquiries.</b><p>Tell us what you need to move, where it needs to go, and when. We’ll discuss your requirements with you.</p><Link href={root+"/about"}>Get to know J&amp;M <ArrowRight/></Link></div></section><section className="jm-section jm-soft"><div className="jm-heading"><div><p>HOW CAN WE HELP?</p><h2>Let’s talk logistics.</h2></div><Link href={root+"/services"}>Explore our approach <ArrowRight/></Link></div><Cards/></section><CTA/></>}
function Services({site}:{site:CustomerSite}){return <><section className="jm-page"><p>TRUCKING &amp; LOGISTICS</p><h1>Your shipment.<br/>Let’s work through the details.</h1><span>{site.pages.services.intro}</span></section><div className="jm-banner"><Image src={site.images.gallery[0].src} alt={site.images.gallery[0].alt} fill/><b>EVERY DETAIL STARTS WITH A CONVERSATION.</b></div><section className="jm-section"><p>WAYS TO START</p><h2>Tell us what you need.</h2><Cards/><aside>Specific services, equipment, cargo types, and service areas are confirmed on inquiry. These topics help start the conversation and do not guarantee availability.</aside></section><CTA/></>}
function About({site}:{site:CustomerSite}){return <><section className="jm-section jm-about"><div><p>ABOUT J&amp;M</p><h1>It starts with<br/>a conversation.</h1><b>{site.pages.about.paragraphs[0]}</b><Link className="jm-quote" href={root+"/contact"}>Get in touch <ArrowRight/></Link></div><figure><Image src={site.images.gallery[1].src} alt={site.images.gallery[1].alt} fill/><figcaption><MapPin/> Our home base <b>Birmingham, Alabama</b></figcaption></figure></section><section className="jm-section jm-soft jm-two"><div><p>PEOPLE BEFORE THE PAPERWORK</p><h2>Let’s start with<br/>what matters to you.</h2></div><div>{site.pages.about.paragraphs.slice(1).map(p=><p key={p}>{p}</p>)}<a href="tel:+12057718234">(205) 771-8234</a></div></section><CTA/></>}
function Contact({site}:{site:CustomerSite}){return <main className="jm-contact"><section className="jm-page"><p>CONTACT J&amp;M</p><h1>Let’s get<br/>the conversation moving.</h1><span>{site.pages.contact.intro}</span></section><div className="jm-contact-options"><article><Phone/><h2>Give us a call</h2><a href="tel:+12057718234">(205) 771-8234</a><p>Speak with Dia Muhammad</p></article><article><Mail/><h2>Send an email</h2><a href="mailto:diamuhammad@yahoo.com">diamuhammad@yahoo.com</a><p>For freight inquiries and questions</p></article><article><MapPin/><h2>Our home base</h2><b>Birmingham, Alabama</b><p>Contact us to discuss your route</p></article></div><section className="jm-form"><CustomerContactForm accent="#f58236" customerSlug={site.slug}/><aside><p>LET’S CONNECT</p><h2>Freight starts with the details.</h2><span>Tell us about your shipment, and J&amp;M will discuss the next step.</span><a href="tel:+12057718234">(205) 771-8234</a><a href="mailto:diamuhammad@yahoo.com">diamuhammad@yahoo.com</a></aside></section></main>}
function Privacy({site}:{site:CustomerSite}){return <section className="jm-section jm-privacy"><p>YOUR INFORMATION</p><h1>Privacy Policy</h1>{site.pages.privacy.body.map(p=><p key={p}>{p}</p>)}</section>}
export function JmWebsite({site,page}:{site:CustomerSite;page:CustomerPage}){return <div className="jm-site"><Nav page={page}/><main>{page==="home"?<Home site={site}/>:page==="services"?<Services site={site}/>:page==="about"?<About site={site}/>:page==="contact"?<Contact site={site}/>:<Privacy site={site}/>}</main><footer className="jm-footer"><Image src="/customers/jm-trucking/brand/logo-light.svg" alt="J&M Trucking Logistics" width={260} height={66}/><span>Trucking &amp; logistics.<br/>A conversation away.</span><nav><Link href={root}>Home</Link><Link href={root+"/about"}>About</Link><Link href={root+"/services"}>Services</Link><Link href={root+"/contact"}>Contact</Link></nav><small>© 2026 J&amp;M Trucking Logistics LLC. Website designed by <a href="https://www.theredspectrum.com/">Red Spectrum</a>.</small></footer>{site.myndy.embed.enabled && <CustomerMyndy agentId={site.myndy.embed.agentId} accent="#101f32" label="Open the J&M Trucking Logistics AI conversation assistant" />}</div>}
