import Image from 'next/image';
import type { CustomerSite } from '@/lib/customers/schema';
import { umgGroups, umgService, umgServices } from '@/lib/customers/umg-services';
import { UmgInquiryForm } from './umg-inquiry-form';
import extraImages from '@/customers/unique-management-group/site/additional-images.json';
import './unique-management.css';

const pages = { home: 'Home', services: 'Services', about: 'About', contact: 'Contact', privacy: 'Privacy' };
export function UniqueManagementWebsite({ site, route = [] }: { site: CustomerSite; route?: string[] }) {
  const root = '/unique-management-group', page = route[0] || 'home', service = route[1] ? umgService(route[1]) : undefined;
  const images = [site.images.hero, ...site.images.gallery, ...extraImages];
  const url = (p: string) => root + (p === 'home' ? '' : '/' + p);
  const photo = (index: number, priority = false) => { const p = images[index]; return <Image src={p.src} alt={p.alt} width={p.width} height={p.height} sizes="(max-width: 760px) 100vw, (max-width: 1100px) 60vw, 850px" priority={priority}/>; };
  const cta = (text = 'Discuss your priorities', href = url('contact')) => <a className="umg-button" href={href}>{text}<span aria-hidden="true">↗</span></a>;
  const label = (text: string) => <p className="umg-eyebrow"><span aria-hidden="true"/>{text}</p>;
  const closing = <section className="umg-closing umg-wrap">{label('A practical next step')}<div><h2>Start with a conversation.<br/><em>Find a clearer direction.</em></h2>{cta()}</div><p>Tell us what you are managing, changing, or bringing to market.</p></section>;
  const serviceLink = (s: typeof umgServices[number]) => url('services/' + s.slug);
  return <div className="umg"><a href="#umg-main" className="umg-skip">Skip to content</a>
    <header className="umg-header umg-wrap"><a className="umg-logo" href={root} aria-label="Unique Management Group LLC home"><Image src={site.branding.logoPath} width={220} height={65} alt="Unique Management Group" priority/></a><nav aria-label="Main navigation">{Object.entries(pages).filter(([p]) => p !== 'privacy').map(([p, title]) => <a key={p} href={url(p)} aria-current={p === page ? 'page' : undefined}>{title}</a>)}</nav><a className="umg-header-contact" href={url('contact')}>Let’s talk <span aria-hidden="true">↗</span></a><details><summary>Menu <span aria-hidden="true">☰</span></summary><nav aria-label="Mobile navigation">{Object.entries(pages).map(([p, title]) => <a key={p} href={url(p)}>{title}</a>)}</nav></details></header>
    <main id="umg-main">
      {page === 'home' && <>
        <section className="umg-hero umg-wrap"><div className="umg-hero-copy">{label('Consulting · Management · Marketing')}<h1>Clear thinking.<br/><em>Practical direction.</em></h1><p>Practical management and consulting support for business and real-estate needs. Connect your operations, business strategy, and market-facing presence.</p><div className="umg-actions">{cta()}<a className="umg-link" href={url('services')}>Explore our services →</a></div><div className="umg-hero-note"><span>BASED IN THE BRONX</span><span>Business priorities. Clear next steps.</span></div></div><figure className="umg-hero-image">{photo(12, true)}<figcaption>Business collaboration · illustrative photography</figcaption><div className="umg-image-tag">Listen.<br/>Analyze. Act.</div></figure></section>
        <div className="umg-service-band umg-wrap"><span>A connected perspective.</span><p>Consulting <b aria-hidden="true">/</b> Management <b aria-hidden="true">/</b> Business visibility</p></div>
        <section className="umg-intro umg-wrap"><div>{label('The Unique perspective')}<h2>Organize the work.<br/><em>Clarify the direction.</em></h2></div><div><p>For business owners, organizations, and entrepreneurs, the next challenge may involve structure, communication, or how the business presents itself to its market.</p><p>Unique Management Group LLC brings consulting and management into the same conversation. We listen to your situation, consider the connected issues, and discuss a practical scope for moving forward.</p><a className="umg-link" href={url('about')}>Our approach ↗</a></div></section>
        <section className="umg-capabilities umg-wrap"><div className="umg-section-head"><div>{label('What we do')}<h2>Three perspectives.<br/><em>Seven connected services.</em></h2></div><a className="umg-link" href={url('services')}>Explore every service ↗</a></div><div className="umg-feature-grid">{[{ title: 'Business & Operations', text: 'Bring more structure to administration, business decisions, general management, and records.', img: 0, slug: 'business-management' }, { title: 'Consulting & Strategy', text: 'Consider organizational change, location decisions, business communication, and visibility in context.', img: 13, slug: 'reorganizational-consulting' }, { title: 'Real Estate Management', text: 'Connect property oversight with the operational priorities of owners and the people involved.', img: 10, slug: 'real-estate-management' }].map((s, i) => <a className="umg-feature" key={s.slug} href={url('services/' + s.slug)}><div>{photo(s.img)}<span className="umg-photo-arrow" aria-hidden="true">↗</span></div>{label('0' + (i + 1) + ' / Areas of focus')}<h3>{s.title}</h3><p>{s.text}</p></a>)}</div></section>
        <section className="umg-approach"><div className="umg-wrap umg-approach-grid"><figure>{photo(1)}<figcaption>Illustrative consulting discussion</figcaption></figure><div>{label('Why start the conversation')}<h2>When the next step<br/><em>needs perspective.</em></h2><p>A growing workload, an organizational change, or an unclear business message can be a useful starting point. The first conversation is about understanding the issue, not prescribing a solution.</p><ol>{[['Listen', 'Understand the priorities, people, and constraints.'], ['Analyze', 'Look at how operations, information, and business communication connect.'], ['Act', 'Agree on an appropriate scope and clear next steps.']].map(([title, text], i) => <li key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></div></section>
        <section className="umg-place umg-wrap"><div>{label('Business visibility, grounded in the business')}<h2>What you do.<br/><em>How you communicate it.</em></h2><p>Marketing begins with a clear view of the business. Discuss how business strategy, communication, and market-facing presentation relate to the work you do.</p><p>Our seven management and consulting services provide the starting framework. The specific support you need is a conversation, not a one-size-fits-all package.</p>{cta('Discuss your business')}</div><figure>{photo(14)}<figcaption>Professional workspace · illustrative setting</figcaption></figure></section>{closing}
      </>}
      {page === 'services' && !service && <>
        <section className="umg-page-title umg-wrap">{label('Consulting & management services')}<h1>Structure for today.<br/><em>Perspective for tomorrow.</em></h1><p>Seven services across business operations, consulting and strategy, and real estate management. Start with the part of the business that needs attention.</p></section>
        {umgGroups.map((group, i) => <section className="umg-service-category umg-wrap" key={group}><div className="umg-category-heading"><div>{label('0' + (i + 1) + ' / Our services')}<h2>{group}</h2></div><figure>{photo([2, 13, 15][i])}</figure></div><div className="umg-service-rows">{umgServices.filter(s => s.group === group).map(s => <article key={s.slug}><h3><a href={serviceLink(s)}>{s.name}</a></h3><p>{s.overview}</p><a className="umg-link" href={serviceLink(s)}>Explore {s.name} ↗</a></article>)}</div></section>)}{closing}
      </>}
      {service && <>
        <section className="umg-detail-hero umg-wrap"><div><a className="umg-link" href={url('services')}>← All services</a>{label(service.group)}<h1>{service.name}</h1><p>{service.overview}</p>{cta('Discuss this service', url('contact') + '?service=' + encodeURIComponent(service.name))}</div><figure>{photo(service.image, true)}<figcaption>Illustrative business photography</figcaption></figure></section>
        <section className="umg-intro umg-wrap"><div>{label('Where it can help')}<h2>Start with<br/><em>the right questions.</em></h2></div><div><ul className="umg-problems">{service.problems.map(text => <li key={text}>{text}</li>)}</ul></div></section>
        <section className="umg-place umg-wrap"><figure>{photo(service.image === 9 ? 15 : service.image === 5 ? 11 : 14)}<figcaption>Illustrative setting, not a client engagement</figcaption></figure><div>{label('Practical business context')}<h2>A connected<br/><em>management perspective.</em></h2><p>{service.context}</p></div></section>
        <section className="umg-values umg-wrap">{label('An approach to the conversation')}<h2>Listen. Analyze. Act.</h2><div>{service.approach.map((text, i) => <article key={text}><span>0{i + 1}</span><h3>{['Understand', 'Review', 'Discuss'][i]}</h3><p>{text}</p></article>)}</div></section>
        <section className="umg-related umg-wrap">{label('Related services')}<h2>Explore the connected work.</h2><nav aria-label="Related services">{umgServices.filter(s => s.slug !== service.slug && (s.group === service.group || s.slug === 'general-management')).slice(0, 3).map(s => <a className="umg-link" key={s.slug} href={serviceLink(s)}>{s.name} ↗</a>)}</nav></section>{closing}
      </>}
      {page === 'about' && <>
        <section className="umg-page-title umg-wrap">{label('About Unique Management Group')}<h1>We listen,<br/><em>analyze, and act.</em></h1><p>A consulting perspective and management discipline for business owners, organizations, and property owners.</p></section><figure className="umg-wide-photo umg-wrap">{photo(7, true)}<figcaption>Illustrative collaboration setting</figcaption></figure>
        <section className="umg-intro umg-wrap"><div>{label('Our mission')}<h2>Make complex work<br/><em>more manageable.</em></h2></div><div><p>Our mission is to simplify complex operations through management and consulting. Clear organization and practical decision support begin with an understanding of the business.</p><p>That includes the way an organization works internally and the way it communicates externally. We bring the operational and consulting perspectives together to discuss a useful direction.</p><p>Contact Unique Management Group LLC to discuss your business priorities.</p></div></section>
        <section className="umg-values umg-wrap">{label('Our values')}<h2>Principles that guide the work.</h2><div>{[['Integrity', 'Lead with honesty and ethics.'], ['Innovation', 'Consider thoughtful ways to address changing business needs.'], ['Accountability', 'Bring responsibility and clarity to the work.'], ['Excellence', 'Approach each engagement with care and professionalism.']].map(([title, text], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
        <section className="umg-place umg-wrap"><figure>{photo(4)}</figure><div>{label('Our vision')}<h2>People. Business.<br/><em>Clearer direction.</em></h2><p>Our vision connects people, business, and real estate management through professionalism and precision.</p><p>We listen, analyze, and act. Business organization, communication, and a clear next step matter more than a ready-made answer.</p>{cta('Explore our services', url('services'))}</div></section>{closing}
      </>}
      {page === 'contact' && <>
        <section className="umg-page-title umg-wrap">{label('Contact Unique Management Group')}<h1>Your priorities.<br/><em>Our starting point.</em></h1><p>Talk with Unique Management Group LLC about consulting, business management, business visibility, or real-estate-oriented management support.</p></section>
        <section className="umg-contact umg-wrap"><div className="umg-contact-info"><h2>Start the conversation.</h2><p>Unique Management Group LLC</p><dl><dt>CALL</dt><dd><a href="tel:+13476663929">347-666-3929</a></dd><dt>EMAIL</dt><dd><a href="mailto:info@uniquemanagementgroup.com">info@uniquemanagementgroup.com</a></dd></dl><p className="umg-small">Please contact us before planning a visit.</p><figure>{photo(11)}<figcaption>New York · illustrative cityscape</figcaption></figure></div><div className="umg-form"><h2>Tell us about<br/>the work.</h2><p>Share the context and the service you would like to discuss.</p><UmgInquiryForm root={root}/><p className="umg-small"><a href={url('privacy')}>Read our privacy notice</a>. Please do not include payment credentials or sensitive personal information.</p></div></section>
      </>}
      {page === 'privacy' && <><section className="umg-page-title umg-wrap">{label('Privacy')}<h1>Clear about<br/><em>your information.</em></h1><p>How information is used when you visit this website or send an inquiry.</p></section><article className="umg-privacy umg-wrap">{[{ h: 'Information you provide', t: 'The inquiry form collects your name, email, phone, optional company, selected service, message, and consent. Unique Management Group LLC uses this information to review and respond to your inquiry.' }, { h: 'Inquiry handling', t: 'Inquiries are stored in the website’s database and an email notification is sent to info@uniquemanagementgroup.com. Hosting, database, and email service providers process information needed to operate this workflow.' }, { h: 'Technical information', t: 'Hosting services process technical request information to deliver and secure the website. Submission checks and rate limiting help protect the inquiry form from misuse.' }, { h: 'Your choices', t: 'You can contact the company by phone or email instead of using the form. To ask about your information or request correction or deletion, contact info@uniquemanagementgroup.com. Please do not submit sensitive personal information or payment credentials.' }, { h: 'Photography', t: 'Photographs illustrate business settings and are not presented as the company’s team, clients, offices, or managed properties.' }].map(s => <section key={s.h}><h2>{s.h}</h2><p>{s.t}</p></section>)}<a className="umg-link" href={url('contact')}>Contact Unique Management Group ↗</a></article></>}
      {page === 'thank-you' && <section className="umg-page-title umg-wrap umg-thanks">{label('Inquiry received')}<h1>Thank you.<br/><em>We have your message.</em></h1><p>Your inquiry has been received by Unique Management Group LLC for review.</p><div className="umg-actions">{cta('Back to Home', root)}<a className="umg-link" href={url('contact')}>Contact the company ↗</a></div></section>}
    </main>
    <footer className="umg-footer"><div className="umg-wrap"><div className="umg-footer-top"><div><a className="umg-footer-logo" href={root}><Image src={site.branding.logoPath} alt="Unique Management Group" width={220} height={65}/></a><p>Consulting perspective.<br/>Management discipline.<br/>Clear business communication.</p></div><nav aria-label="Footer navigation">{Object.entries(pages).map(([p, title]) => <a href={url(p)} key={p}>{title}</a>)}</nav><div className="umg-footer-contact"><a href="tel:+13476663929">347-666-3929</a><a href="mailto:info@uniquemanagementgroup.com">info@uniquemanagementgroup.com</a></div></div><div className="umg-footer-bottom"><span>© 2026 Unique Management Group LLC</span><span>Website designed by <a href="https://www.theredspectrum.com/">Red Spectrum</a>.</span><span>Photography is illustrative.</span></div></div></footer>
  </div>;
}
