import Image from 'next/image';
import type {CustomerPage,CustomerSite} from '@/lib/customers/schema';
import './unique-management.css';

const pages={home:'Home',services:'Services',about:'About',contact:'Contact',privacy:'Privacy'};
const serviceImages=[3,4,5,6,7,8,9];
const prompts=['Where does administrative work slow your day?','What needs to change as your business evolves?','What should your next location make possible?','Where could your business operate more effectively?','Which organizational challenges need a clearer direction?','How are important records organized and accessed?','What support does your property need?'];
export function UniqueManagementWebsite({site,page}:{site:CustomerSite;page:CustomerPage}){
 const root='/'+site.slug,images=[site.images.hero,...site.images.gallery];
 const url=(p:string)=>root+(p==='home'?'':'/'+p);
 const photo=(index:number,priority=false)=>{const p=images[index];return <Image src={p.src} alt={p.alt} width={p.width} height={p.height} sizes="(max-width: 700px) 100vw, (max-width: 1100px) 60vw, 850px" priority={priority}/>;};
 const cta=(label='Discuss your needs',href=url('contact'),light=false)=><a className={'umg-button'+(light?' umg-button-light':'')} href={href}>{label}<span aria-hidden="true">↗</span></a>;
 const label=(text:string)=><p className="umg-eyebrow"><span aria-hidden="true"/>{text}</p>;
  const closing=<section className="umg-closing umg-wrap">{label('A practical next step')}<div><h2>Talk through the work.<br/><em>Start with the facts.</em></h2>{cta('Contact the office')}</div><p>Tell us what you are managing, changing, or planning.</p></section>;
 return <div className="umg"><a href="#umg-main" className="umg-skip">Skip to content</a><div className="umg-review">PRIVATE DESIGN PREVIEW <span>·</span> Unique Management Group LLC</div>
 <header className="umg-header umg-wrap"><a className="umg-logo" href={root} aria-label="Unique Management Group LLC home"><Image src={site.branding.logoPath} width={220} height={65} alt="Unique Management Group" priority/></a><nav aria-label="Main navigation">{Object.entries(pages).filter(([p])=>p!=='privacy').map(([p,title])=><a key={p} href={url(p)} aria-current={p===page?'page':undefined}>{title}</a>)}</nav><a className="umg-header-contact" href={url('contact')}>Let’s talk <span aria-hidden="true">↗</span></a><details><summary>Menu <span aria-hidden="true">☰</span></summary><nav aria-label="Mobile navigation">{Object.entries(pages).map(([p,title])=><a key={p} href={url(p)} aria-current={p===page?'page':undefined}>{title}</a>)}</nav></details></header>
 <main id="umg-main">
 {page==='home'&&<>
  <section className="umg-hero umg-wrap"><div className="umg-hero-copy">{label('Management for business and property')}<h1>Practical help<br/><em>for complex work.</em></h1><p>Unique Management Group LLC supports business operations, organizational decisions, and real estate management from the Bronx, New York.</p><div className="umg-actions">{cta('Discuss your needs')}<a className="umg-link" href={url('services')}>See what we do <span aria-hidden="true">→</span></a></div><div className="umg-hero-note"><span>BASED IN THE BRONX</span><span>Start with a conversation about the work.</span></div></div><figure className="umg-hero-image">{photo(0,true)}<figcaption><span>ILLUSTRATIVE WORKSPACE PHOTOGRAPHY</span><span aria-hidden="true">01 —</span></figcaption><div className="umg-image-tag">Management<br/>with context.</div></figure></section>
  <div className="umg-service-band umg-wrap"><span>Areas we support.</span><p>Business operations <b aria-hidden="true">/</b> Administration <b aria-hidden="true">/</b> Property management</p></div>
  <section className="umg-intro umg-wrap"><div>{label('The Unique perspective')}<h2>A practical partner<br/><em>for the work at hand.</em></h2></div><div><p>Management issues rarely sit in one category. People, processes, records, locations, and property can all affect the same decision.</p><p>We begin by listening to the situation, then help define a useful scope for the next step.</p><a className="umg-link" href={url('about')}>About the company <span aria-hidden="true">↗</span></a></div></section>
  <section className="umg-capabilities umg-wrap"><div className="umg-section-head"><div>{label('Where we can help')}<h2>Different work.<br/><em>Clearer next steps.</em></h2></div><a className="umg-link" href={url('services')}>View all seven services <span aria-hidden="true">↗</span></a></div><div className="umg-feature-grid">{[{title:'Business & strategy',text:'Review structure, performance, and organizational change with a practical lens.',img:1,id:'business-management'},{title:'Operations & administration',text:'Bring more order to administration, records, and location decisions.',img:2,id:'administrative-management'},{title:'Real estate management',text:'Discuss property oversight, maintenance, rentals, and tenant relations.',img:9,id:'real-estate-management'}].map((s,i)=><a className="umg-feature" href={url('services')+'#'+s.id} key={s.title}><div>{photo(s.img)}<span className="umg-photo-arrow" aria-hidden="true">↗</span></div><p className="umg-eyebrow">0{i+1} / CAPABILITIES</p><h3>{s.title}</h3><p>{s.text}</p></a>)}</div></section>
  <section className="umg-approach"><div className="umg-wrap umg-approach-grid"><figure>{photo(7)}<figcaption>Illustrative meeting photography</figcaption></figure><div>{label('How we work')}<h2>Start with the situation.<br/><em>Then make a plan.</em></h2><p>Our approach is straightforward: listen to the priorities, look at how the work is organized, and agree on a sensible next step.</p><ol><li><span>01</span><div><h3>Listen</h3><p>Understand the priorities, people, and constraints.</p></div></li><li><span>02</span><div><h3>Review</h3><p>Look at the processes, records, or property involved.</p></div></li><li><span>03</span><div><h3>Discuss</h3><p>Set an appropriate scope for the work ahead.</p></div></li></ol></div></div></section>
  <section className="umg-place umg-wrap"><div>{label('A New York perspective')}<h2>Based in the Bronx.<br/><em>Focused on the work.</em></h2><p>Unique Management Group LLC works across the connected concerns of business, people, and real estate.</p><p>Service availability and scope depend on the situation. A conversation is the right place to begin.</p><a className="umg-link" href={url('contact')}>Contact the company <span aria-hidden="true">↗</span></a></div><figure>{photo(11)}<figcaption>New York cityscape · illustrative, not a managed property</figcaption></figure></section>{closing}</>}
 {page==='services'&&<><section className="umg-page-title umg-wrap">{label('What we do')}<h1>Support for the work<br/><em>behind the business.</em></h1><p>Seven services covering administration, organizational change, business management, records, locations, and real estate. We can discuss which area fits your situation.</p></section><nav className="umg-service-index umg-wrap" aria-label="Service directory">{site.services.map((s,i)=><a key={s.name} href={'#'+s.name.toLowerCase().replaceAll(' ','-')}><span>0{i+1}</span>{s.name}<span aria-hidden="true">↓</span></a>)}</nav><div className="umg-wrap">{site.services.map((s,i)=><section id={s.name.toLowerCase().replaceAll(' ','-')} className={'umg-service-detail '+(i%2?'umg-reverse':'')} key={s.name}><figure>{photo(serviceImages[i])}<figcaption>Illustrative photography · not a client engagement</figcaption></figure><div>{label('0'+(i+1)+' / MANAGEMENT & CONSULTING')}<h2>{s.name}</h2><p>{s.description}</p><div className="umg-prompt"><span>A useful starting question</span><h3>{prompts[i]}</h3></div>{cta('Discuss this service',url('contact')+'?service='+encodeURIComponent(s.name))}</div></section>)}</div>{closing}</>}
 {page==='about'&&<><section className="umg-page-title umg-wrap">{label('About Unique Management Group')}<h1>Management starts<br/><em>with listening.</em></h1><p>A practical management perspective for people, businesses, and property owners.</p></section><figure className="umg-wide-photo umg-wrap">{photo(10,true)}<figcaption>Illustrative workspace · not a company office</figcaption></figure><section className="umg-intro umg-wrap"><div>{label('Our purpose')}<h2>Make the complex<br/><em>more manageable.</em></h2></div><div><p>Unique Management Group was built around a straightforward mission: to simplify complex operations through management and consulting.</p><p>Our official company philosophy brings together structure, clarity, and execution. From organizational change to everyday operations and property oversight, we start by understanding what matters to you.</p><p>Owner and customer contact: Aminul Haque. Based in the Bronx, New York.</p></div></section><section className="umg-values umg-wrap">{label('What guides us')}<h2>Principles behind<br/><em>the perspective.</em></h2><div>{[{n:'Integrity',t:'Lead with honesty and ethics.'},{n:'Innovation',t:'Look for smarter ways to address modern challenges.'},{n:'Accountability',t:'Take ownership of the work and the decisions behind it.'},{n:'Excellence',t:'Bring care and professionalism to every engagement.'}].map((v,i)=><article key={v.n}><span>0{i+1}</span><h3>{v.n}</h3><p>{v.t}</p></article>)}</div></section><section className="umg-place umg-wrap"><figure>{photo(1)}<figcaption>Illustrative collaboration setting</figcaption></figure><div>{label('Our outlook')}<h2>Connected thinking.<br/><em>Practical direction.</em></h2><p>Our vision is to bridge people, business, and property management through professionalism and precision.</p><p>We listen, analyze, and act. Your priorities provide the starting point; the conversation helps define what comes next.</p>{cta('Explore our services',url('services'))}</div></section>{closing}</>}
 {page==='contact'&&<><section className="umg-page-title umg-wrap">{label('Contact the company')}<h1>Talk through<br/><em>the work.</em></h1><p>Tell us what you’re working through. Connect with Aminul Haque to discuss your business, operations, or property management needs.</p></section><section className="umg-contact umg-wrap"><div className="umg-contact-info"><h2>Start here.</h2><p>AMINUL HAQUE<br/>Unique Management Group LLC</p><dl><dt>CALL</dt><dd><a href="tel:+13476663929">347-666-3929 <span aria-hidden="true">↗</span></a></dd><dt>EMAIL</dt><dd><a href="mailto:info@uniquemanagementgroup.com">info@uniquemanagementgroup.com <span aria-hidden="true">↗</span></a></dd><dt>BUSINESS ADDRESS</dt><dd><address>2505 AQUEDUCT AVE<br/>STE 5E<br/>BRONX, NY 10458</address></dd></dl><p className="umg-small">Please contact us before planning a visit. Walk-in availability and opening hours are not listed.</p><figure>{photo(11)}<figcaption>New York · illustrative cityscape</figcaption></figure></div><div className="umg-form"><h2>Your next step<br/>starts with context.</h2><p id="umg-form-note">This preview form is inactive. Nothing entered here is sent. Please use the phone or email links to contact the business directly.</p><fieldset disabled aria-describedby="umg-form-note"><legend>Inquiry preview</legend><label htmlFor="umg-name">Your name<input id="umg-name" autoComplete="off" placeholder="Full name"/></label><label htmlFor="umg-email">Email address<input id="umg-email" type="email" autoComplete="off" placeholder="you@example.com"/></label><label htmlFor="umg-service">What would you like to discuss?<select id="umg-service" defaultValue=""><option value="">Select a service</option>{site.services.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label htmlFor="umg-message">A little about your needs<textarea id="umg-message" rows={5} placeholder="Share your priorities or questions"/></label><button type="button">Form delivery inactive <span aria-hidden="true">↗</span></button></fieldset><p className="umg-small">Please avoid sharing sensitive personal or financial information. <a href={url('privacy')}>Read the preview privacy notice.</a></p></div></section></>}
 {page==='privacy'&&<><section className="umg-page-title umg-wrap">{label('Privacy / preview notice')}<h1>Clear about<br/><em>your information.</em></h1><p>This notice describes the current review preview. The business must review its final privacy arrangements before launch.</p></section><article className="umg-privacy umg-wrap"><p className="umg-eyebrow">LAST UPDATED · SEPTEMBER 29, 2026</p>{[{h:'This website preview',t:'This is a redesign preview for Unique Management Group LLC. It does not replace the current official website.'},{h:'Contacting the business',t:'The inquiry form is disabled and does not submit information. Telephone and email links open your chosen application. If you contact the business directly, the information you choose to send is handled through that communication channel.'},{h:'Hosting and technical information',t:'Hosting infrastructure may process technical request information to deliver and secure these pages. Final hosting, retention periods, service providers, and applicable privacy rights must be confirmed before launch.'},{h:'Preview integrations',t:'Lead delivery, payment features, and an AI assistant have not been activated for this customer preview. Images and brand assets are served through the website rather than third-party image embeds.'},{h:'Questions',t:'For questions about the business or the final privacy notice, contact info@uniquemanagementgroup.com or call 347-666-3929.'}].map(s=><section key={s.h}><h2>{s.h}</h2><p>{s.t}</p></section>)}<a className="umg-link" href={url('contact')}>Contact Unique Management Group <span aria-hidden="true">↗</span></a></article></>}
 </main><footer className="umg-footer"><div className="umg-wrap"><div className="umg-footer-top"><div><a className="umg-footer-logo" href={root}><Image src={site.branding.logoPath} alt="Unique Management Group" width={220} height={65}/></a><p>Managing people, business<br/>and real estate with clarity.</p></div><nav aria-label="Footer navigation">{Object.entries(pages).map(([p,title])=><a href={url(p)} key={p}>{title}</a>)}</nav><div className="umg-footer-contact"><a href="tel:+13476663929">347-666-3929</a><a href="mailto:info@uniquemanagementgroup.com">info@uniquemanagementgroup.com</a><p>2505 Aqueduct Ave, Ste 5E<br/>Bronx, NY 10458</p></div></div><div className="umg-footer-bottom"><span>© 2026 Unique Management Group LLC</span><span>Website designed by <a href="https://www.theredspectrum.com/">Red Spectrum</a>.</span><span>Photography is illustrative.</span></div></div></footer></div>;
}
