import Image from 'next/image';
import type {CustomerPage,CustomerSite} from '@/lib/customers/schema';
import './unique-management.css';

const pages={home:'Home',services:'Services',about:'About',contact:'Contact',privacy:'Privacy'};
const serviceImages=[3,4,5,6,7,8,9];
const prompts=['Where does administrative work slow your day?','What needs to change as your business evolves?','What should your next location make possible?','Where could your business operate more effectively?','Which organizational challenges need a clearer direction?','How are important records organized and accessed?','What support does your property need?'];
export function UniqueManagementWebsite({site,page}:{site:CustomerSite;page:CustomerPage}){
 const root='/'+site.slug,images=[site.images.hero,...site.images.gallery];
 const url=(p:string)=>root+(p==='home'?'':'/'+p);
 const photo=(index:number,priority=false)=>{const p=images[index];return <Image src={p.src} alt={p.alt} width={p.width} height={p.height} sizes="(max-width: 700px) 100vw, (max-width: 1100px) 60vw, 850px" priority={priority}/>;};
 const cta=(label='Discuss your needs',href=url('contact'),light=false)=><a className={'umg-button'+(light?' umg-button-light':'')} href={href}>{label}<span aria-hidden="true">↗</span></a>;
 const label=(text:string)=><p className="umg-eyebrow"><span aria-hidden="true"/>{text}</p>;
 const closing=<section className="umg-closing umg-wrap">{label('A clearer next step')}<div><h2>Bring your questions.<br/><em>Let’s find direction.</em></h2>{cta('Start a conversation')}</div><p>Business, operations, or property. Tell us what you have in mind.</p></section>;
 return <div className="umg"><a href="#umg-main" className="umg-skip">Skip to content</a><div className="umg-review">PRIVATE DESIGN PREVIEW <span>·</span> Unique Management Group LLC</div>
 <header className="umg-header umg-wrap"><a className="umg-logo" href={root} aria-label="Unique Management Group LLC home"><Image src={site.branding.logoPath} width={220} height={65} alt="Unique Management Group" priority/></a><nav aria-label="Main navigation">{Object.entries(pages).filter(([p])=>p!=='privacy').map(([p,title])=><a key={p} href={url(p)} aria-current={p===page?'page':undefined}>{title}</a>)}</nav><a className="umg-header-contact" href={url('contact')}>Let’s talk <span aria-hidden="true">↗</span></a><details><summary>Menu <span aria-hidden="true">☰</span></summary><nav aria-label="Mobile navigation">{Object.entries(pages).map(([p,title])=><a key={p} href={url(p)} aria-current={p===page?'page':undefined}>{title}</a>)}</nav></details></header>
 <main id="umg-main">
 {page==='home'&&<>
 <section className="umg-hero umg-wrap"><div className="umg-hero-copy">{label('Business. People. Property.')}<h1>Complexity,<br/><em>managed.</em></h1><p>Clearer operations. Stronger direction. Management and consulting for businesses and property owners ready to move forward.</p><div className="umg-actions">{cta()}<a className="umg-link" href={url('services')}>Explore our services <span aria-hidden="true">→</span></a></div><div className="umg-hero-note"><span>BASED IN THE BRONX</span><span>A considered approach to management.</span></div></div><figure className="umg-hero-image">{photo(0,true)}<figcaption><span>STRUCTURE / CLARITY / EXECUTION</span><span aria-hidden="true">01 —</span></figcaption><div className="umg-image-tag">A better way<br/>to move forward.</div></figure></section>
 <div className="umg-service-band umg-wrap"><span>One connected perspective.</span><p>Business management <b aria-hidden="true">/</b> Operational consulting <b aria-hidden="true">/</b> Real estate management</p></div>
 <section className="umg-intro umg-wrap"><div>{label('The Unique perspective')}<h2>Good management<br/>creates <em>room to grow.</em></h2></div><div><p>When people, processes, and property pull in different directions, progress gets harder. Unique Management Group brings a practical management perspective to the work that connects them.</p><p>Our mission is to simplify complex operations, improve efficiency, and support lasting growth.</p><a className="umg-link" href={url('about')}>Get to know Unique <span aria-hidden="true">↗</span></a></div></section>
 <section className="umg-capabilities umg-wrap"><div className="umg-section-head"><div>{label('Our expertise')}<h2>Different needs.<br/><em>One clear direction.</em></h2></div><a className="umg-link" href={url('services')}>All seven services <span aria-hidden="true">↗</span></a></div><div className="umg-feature-grid">{[{title:'Business & strategy',text:'A clearer view of structure, performance, and organizational change.',img:1,id:'business-management'},{title:'Operations & administration',text:'Bring focus to everyday administration, records, and location decisions.',img:2,id:'administrative-management'},{title:'Real estate management',text:'A connected perspective on property oversight, tenants, and maintenance.',img:9,id:'real-estate-management'}].map((s,i)=><a className="umg-feature" href={url('services')+'#'+s.id} key={s.title}><div>{photo(s.img)}<span className="umg-photo-arrow" aria-hidden="true">↗</span></div><p className="umg-eyebrow">0{i+1} / CAPABILITIES</p><h3>{s.title}</h3><p>{s.text}</p></a>)}</div></section>
 <section className="umg-approach"><div className="umg-wrap umg-approach-grid"><figure>{photo(10)}<figcaption>Illustrative workspace photography</figcaption></figure><div>{label('How we approach the work')}<h2>Listen closely.<br/>Think clearly.<br/><em>Move purposefully.</em></h2><p>Our approach starts with understanding your situation. We listen, analyze, and act — connecting the challenges you face with a considered direction.</p><ol><li><span>01</span><div><h3>Listen</h3><p>Start with your priorities and the challenges behind them.</p></div></li><li><span>02</span><div><h3>Analyze</h3><p>Look at how your people, processes, and assets work together.</p></div></li><li><span>03</span><div><h3>Act</h3><p>Discuss an appropriate scope and agree on next steps.</p></div></li></ol></div></div></section>
 <section className="umg-place umg-wrap"><div>{label('A New York perspective')}<h2>Grounded here.<br/><em>Focused on you.</em></h2><p>Based in the Bronx, Unique Management Group LLC works at the intersection of business, people, and real estate.</p><p>Start a conversation about your needs and confirm service availability for your location.</p><a className="umg-link" href={url('contact')}>Connect with Aminul Haque <span aria-hidden="true">↗</span></a></div><figure>{photo(11)}<figcaption>New York cityscape · illustrative, not a managed property</figcaption></figure></section>{closing}</>}
 {page==='services'&&<><section className="umg-page-title umg-wrap">{label('What we do')}<h1>Better structure.<br/><em>Greater clarity.</em></h1><p>Seven complementary services for the decisions, operations, and properties that shape your business. Let’s discuss the support your situation calls for.</p></section><nav className="umg-service-index umg-wrap" aria-label="Service directory">{site.services.map((s,i)=><a key={s.name} href={'#'+s.name.toLowerCase().replaceAll(' ','-')}><span>0{i+1}</span>{s.name}<span aria-hidden="true">↓</span></a>)}</nav><div className="umg-wrap">{site.services.map((s,i)=><section id={s.name.toLowerCase().replaceAll(' ','-')} className={'umg-service-detail '+(i%2?'umg-reverse':'')} key={s.name}><figure>{photo(serviceImages[i])}<figcaption>Illustrative photography · not a client engagement</figcaption></figure><div>{label('0'+(i+1)+' / MANAGEMENT & CONSULTING')}<h2>{s.name}</h2><p>{s.description}</p><div className="umg-prompt"><span>A useful starting question</span><h3>{prompts[i]}</h3></div>{cta('Discuss this service',url('contact')+'?service='+encodeURIComponent(s.name))}</div></section>)}</div>{closing}</>}
 {page==='about'&&<><section className="umg-page-title umg-wrap">{label('About Unique Management Group')}<h1>Structure. Clarity.<br/><em>Execution.</em></h1><p>A practical management perspective for people, businesses, and property owners.</p></section><figure className="umg-wide-photo umg-wrap">{photo(10,true)}<figcaption>Illustrative workspace · not a company office</figcaption></figure><section className="umg-intro umg-wrap"><div>{label('Our purpose')}<h2>Make the complex<br/><em>more manageable.</em></h2></div><div><p>Unique Management Group was built around a straightforward mission: to simplify complex operations through management and consulting.</p><p>Our official company philosophy brings together structure, clarity, and execution. From organizational change to everyday operations and property oversight, we start by understanding what matters to you.</p><p>Owner and customer contact: Aminul Haque. Based in the Bronx, New York.</p></div></section><section className="umg-values umg-wrap">{label('What guides us')}<h2>Principles behind<br/><em>the perspective.</em></h2><div>{[{n:'Integrity',t:'Lead with honesty and ethics.'},{n:'Innovation',t:'Look for smarter ways to address modern challenges.'},{n:'Accountability',t:'Take ownership of the work and the decisions behind it.'},{n:'Excellence',t:'Bring care and professionalism to every engagement.'}].map((v,i)=><article key={v.n}><span>0{i+1}</span><h3>{v.n}</h3><p>{v.t}</p></article>)}</div></section><section className="umg-place umg-wrap"><figure>{photo(1)}<figcaption>Illustrative collaboration setting</figcaption></figure><div>{label('Our outlook')}<h2>Connected thinking.<br/><em>Practical direction.</em></h2><p>Our vision is to bridge people, business, and property management through professionalism and precision.</p><p>We listen, analyze, and act. Your priorities provide the starting point; the conversation helps define what comes next.</p>{cta('Explore our services',url('services'))}</div></section>{closing}</>}
 {page==='contact'&&<><section className="umg-page-title umg-wrap">{label('Let’s connect')}<h1>A conversation.<br/><em>A clearer path.</em></h1><p>Tell us what you’re working through. Connect with Aminul Haque to discuss your business, operations, or property management needs.</p></section><section className="umg-contact umg-wrap"><div className="umg-contact-info"><h2>Start here.</h2><p>AMINUL HAQUE<br/>Unique Management Group LLC</p><dl><dt>CALL</dt><dd><a href="tel:+13476663929">347-666-3929 <span aria-hidden="true">↗</span></a></dd><dt>EMAIL</dt><dd><a href="mailto:info@uniquemanagementgroup.com">info@uniquemanagementgroup.com <span aria-hidden="true">↗</span></a></dd><dt>BUSINESS ADDRESS</dt><dd><address>2505 AQUEDUCT AVE<br/>STE 5E<br/>BRONX, NY 10458</address></dd></dl><p className="umg-small">Please contact us before planning a visit. Walk-in availability and opening hours are not listed.</p><figure>{photo(11)}<figcaption>New York · illustrative cityscape</figcaption></figure></div><div className="umg-form"><h2>Your next step<br/>starts with context.</h2><p id="umg-form-note">This preview form is inactive. Nothing entered here is sent. Please use the phone or email links to contact the business directly.</p><fieldset disabled aria-describedby="umg-form-note"><legend>Inquiry preview</legend><label htmlFor="umg-name">Your name<input id="umg-name" autoComplete="off" placeholder="Full name"/></label><label htmlFor="umg-email">Email address<input id="umg-email" type="email" autoComplete="off" placeholder="you@example.com"/></label><label htmlFor="umg-service">What would you like to discuss?<select id="umg-service" defaultValue=""><option value="">Select a service</option>{site.services.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label htmlFor="umg-message">A little about your needs<textarea id="umg-message" rows={5} placeholder="Share your priorities or questions"/></label><button type="button">Form delivery inactive <span aria-hidden="true">↗</span></button></fieldset><p className="umg-small">Please avoid sharing sensitive personal or financial information. <a href={url('privacy')}>Read the preview privacy notice.</a></p></div></section></>}
 {page==='privacy'&&<><section className="umg-page-title umg-wrap">{label('Privacy / preview notice')}<h1>Clear about<br/><em>your information.</em></h1><p>This notice describes the current review preview. The business must review its final privacy arrangements before launch.</p></section><article className="umg-privacy umg-wrap"><p className="umg-eyebrow">LAST UPDATED · SEPTEMBER 29, 2026</p>{[{h:'This website preview',t:'This is a redesign preview for Unique Management Group LLC. It does not replace the current official website.'},{h:'Contacting the business',t:'The inquiry form is disabled and does not submit information. Telephone and email links open your chosen application. If you contact the business directly, the information you choose to send is handled through that communication channel.'},{h:'Hosting and technical information',t:'Hosting infrastructure may process technical request information to deliver and secure these pages. Final hosting, retention periods, service providers, and applicable privacy rights must be confirmed before launch.'},{h:'Preview integrations',t:'Lead delivery, payment features, and an AI assistant have not been activated for this customer preview. Images and brand assets are served through the website rather than third-party image embeds.'},{h:'Questions',t:'For questions about the business or the final privacy notice, contact info@uniquemanagementgroup.com or call 347-666-3929.'}].map(s=><section key={s.h}><h2>{s.h}</h2><p>{s.t}</p></section>)}<a className="umg-link" href={url('contact')}>Contact Unique Management Group <span aria-hidden="true">↗</span></a></article></>}
 </main><footer className="umg-footer"><div className="umg-wrap"><div className="umg-footer-top"><div><a className="umg-footer-logo" href={root}><Image src={site.branding.logoPath} alt="Unique Management Group" width={220} height={65}/></a><p>Managing people, business<br/>and real estate with clarity.</p></div><nav aria-label="Footer navigation">{Object.entries(pages).map(([p,title])=><a href={url(p)} key={p}>{title}</a>)}</nav><div className="umg-footer-contact"><a href="tel:+13476663929">347-666-3929</a><a href="mailto:info@uniquemanagementgroup.com">info@uniquemanagementgroup.com</a><p>2505 Aqueduct Ave, Ste 5E<br/>Bronx, NY 10458</p></div></div><div className="umg-footer-bottom"><span>© 2026 Unique Management Group LLC</span><span>Website designed by <a href="https://www.theredspectrum.com/">Red Spectrum</a>.</span><span>Photography is illustrative.</span></div></div></footer></div>;
}
