import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, ChevronDown, Menu, Salad, Dumbbell, HeartPulse, Laptop, UserRound } from "lucide-react";
import { CustomerContactForm } from "@/components/customer-contact-form";
import { CustomerMyndy } from "./customer-myndy";
import { blogArticles, blogCategories, getArticle } from "@/lib/customers/vitality-blog";
import type { CustomerSite } from "@/lib/customers/schema";
import "./vitality.css";

const root = "/360-vitality-fitness";
const services = [
  ["Online Fitness Coaching", "online-fitness-coaching", "Personalized workouts and ongoing guidance that work around your schedule.", Laptop],
  ["Personal Training", "personal-training", "One-on-one guidance shaped around your goals, ability and routine.", UserRound],
  ["Nutrition Coaching", "nutrition-coaching", "Practical nutrition accountability without restrictive promises or extremes.", Salad],
  ["Body Assessment", "body-assessment", "A fitness-focused starting point for understanding movement and planning next steps.", HeartPulse],
  ["21-Day Fitness Challenge", "21-day-fitness-challenge", "A short, supportive program designed to build momentum and consistency.", Dumbbell],
] as const;
const href = (path = "") => `${root}${path}`;
const blogImage = (src: string) => `/customers/360-vitality-fitness${src}`;

function Header() {
  return <header className="vf-header"><div className="vf-wrap vf-header-inner"><Link href={root} className="vf-brand" aria-label="360 Vitality Fitness home"><Image src="/customers/360-vitality-fitness/brand/logo.png" alt="360 Vitality Fitness LLC" width={160} height={92} priority /></Link><nav className="vf-desktop-nav" aria-label="Primary navigation"><Link href={root}>Home</Link><Link href={href("/about")}>About</Link><details><summary>Services <ChevronDown aria-hidden="true" /></summary><div>{services.map(([title, slug]) => <Link key={slug} href={href(`/${slug}`)}>{title}</Link>)}<Link href={href("/services")}>View all services</Link></div></details><Link href={href("/blog")}>Blog</Link><Link href={href("/contact")}>Contact</Link></nav><div className="vf-actions"><a href="tel:+18776967333">(877) 696-7333</a><Link className="vf-button vf-button-small" href={href("/contact")}>Free Consultation</Link></div><details className="vf-mobile-menu"><summary aria-label="Open navigation"><Menu aria-hidden="true" /></summary><nav aria-label="Mobile navigation"><Link href={root}>Home</Link><Link href={href("/about")}>About Angela</Link><Link href={href("/services")}>Services</Link>{services.map(([title, slug]) => <Link key={slug} href={href(`/${slug}`)}>{title}</Link>)}<Link href={href("/blog")}>Blog</Link><Link href={href("/contact")}>Contact</Link><a href="tel:+18776967333">(877) 696-7333</a></nav></details></div></header>;
}
function Footer() { return <footer className="vf-footer"><div className="vf-wrap vf-footer-grid"><div><Image src="/customers/360-vitality-fitness/brand/logo.png" alt="360 Vitality Fitness LLC" width={172} height={98}/><p>Personalized fitness, mobility and nutrition guidance for busy adults in Chicago and online.</p><p>Consultations and coaching sessions are available by appointment.</p></div><div><h2>Explore</h2><Link href={href("/about")}>About Angela</Link><Link href={href("/services")}>Services</Link><Link href={href("/blog")}>Blog</Link><Link href={href("/contact")}>Contact</Link></div><div><h2>Services</h2>{services.map(([title, slug]) => <Link key={slug} href={href(`/${slug}`)}>{title}</Link>)}</div><div><h2>Connect</h2><a href="tel:+18776967333">(877) 696-7333</a><a href="mailto:get360vitalityfitness@gmail.com">get360vitalityfitness@gmail.com</a><span>Chicago, IL</span></div></div><div className="vf-wrap vf-footer-bottom"><span>© 2026 360 Vitality Fitness LLC. Website designed by <a href="https://www.theredspectrum.com/" target="_blank" rel="noreferrer">Red Spectrum</a>.</span><nav><Link href={href("/privacy")}>Privacy</Link><Link href={href("/terms-and-conditions")}>Terms</Link><Link href={href("/health-and-fitness-disclaimer")}>Health Disclaimer</Link></nav></div></footer>; }
function Hero({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <section className="vf-page-hero"><div className="vf-wrap"><p>{eyebrow}</p><h1>{title}</h1><span>{description}</span></div></section>; }
function ServiceCards() { return <div className="vf-service-grid">{services.map(([title, slug, text, Icon]) => <article key={slug}><Icon aria-hidden="true"/><h3>{title}</h3><p>{text}</p><Link href={href(`/${slug}`)}>Learn More <ArrowRight aria-hidden="true" /></Link></article>)}</div>; }
function Home() { return <><section className="vf-hero"><Image src="/customers/360-vitality-fitness/images/hero.png" alt="A fitness coach guiding two adults through approachable strength exercises" fill priority sizes="100vw"/><div/><div className="vf-wrap vf-hero-copy"><p>ONLINE COACHING · CHICAGO SESSIONS BY REQUEST</p><h1>Build Strength. Move Better. Feel Like Yourself Again.</h1><span>Personalized online fitness, nutrition and mobility coaching designed for busy adults who want sustainable progress without extreme routines.</span><nav><Link className="vf-button" href={href("/contact")}>Request a Free Consultation <ArrowRight /></Link><Link className="vf-button vf-button-white" href={href("/services")}>Explore Our Services</Link></nav><small>Temporary illustrative image — replace with customer-approved photography.</small></div></section><section className="vf-section vf-white"><div className="vf-wrap vf-split"><div><p>COACHING THAT MEETS YOU WHERE YOU ARE</p><h2>Fitness Guidance Built Around Your Real Life</h2></div><span>You do not need a perfect schedule or years of gym experience to improve your health. 360 Vitality Fitness LLC provides practical coaching that adapts to your current ability, personal goals and daily routine.</span></div></section><section className="vf-section"><div className="vf-wrap"><p className="vf-kicker">WAYS TO WORK TOGETHER</p><h2>Support for your next healthy step</h2><ServiceCards /></div></section><section className="vf-section vf-navy"><div className="vf-wrap vf-who"><div><p>WHO WE HELP</p><h2>Progress that feels practical—and personal.</h2><span>Clear guidance, encouraging accountability and plans designed for real schedules.</span></div><ul>{["Busy adults and professionals", "Adults over 40", "Fitness beginners", "People returning to exercise", "Clients seeking better mobility", "People wanting realistic nutrition support"].map(x => <li key={x}><Check />{x}</li>)}</ul></div></section><section className="vf-section vf-white"><div className="vf-wrap"><div className="vf-center"><p> SIMPLE, SUPPORTIVE PROCESS</p><h2>How it works</h2></div><div className="vf-steps">{["Tell Us About Your Goals", "Receive Your Personalized Plan", "Build Consistent, Sustainable Progress"].map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3></article>)}</div></div></section><section className="vf-section"><div className="vf-wrap vf-resources"><p>WELLNESS RESOURCES</p><h2>Practical guidance for your next step</h2><div>{blogArticles.slice(0,3).map(article=><article key={article.slug}><Link href={href(`/blog/${article.slug}`)}><Image src={blogImage(article.image)} alt={article.imageAlt} width={1536} height={1024}/></Link><small>{article.category}</small><h3><Link href={href(`/blog/${article.slug}`)}>{article.title}</Link></h3><Link href={href(`/blog/${article.slug}`)}>Read article <ArrowRight/></Link></article>)}</div><Link className="vf-button" href={href("/blog")}>Explore all articles</Link></div></section><Cta /></>; }
function Cta() { return <section className="vf-cta"><div className="vf-wrap"><div><p>READY WHEN YOU ARE</p><h2>Ready to Take Your Next Healthy Step?</h2><span>Tell us what you want to improve, and we’ll help you identify a practical place to begin.</span></div><nav><Link className="vf-button vf-button-white" href={href("/contact")}>Request a Free Consultation</Link><a className="vf-button vf-button-outline" href="tel:+18776967333">Call (877) 696-7333</a></nav></div></section>; }
function Services({ slug }: { slug?: string }) { const service = services.find(([, key]) => key === slug); if (service) return <><Hero eyebrow="Services" title={service[0]} description={service[2]}/><section className="vf-section"><div className="vf-wrap vf-narrow"><h2>Focused support for your goals</h2><p>This service is offered as described on the existing 360 Vitality Fitness website. Availability, scheduling and the right starting point are confirmed directly with the business.</p><ul className="vf-check-list">{["Personalized guidance", "Beginner-friendly pacing", "Practical support for real schedules", "A consultation before plans are confirmed"].map(x=><li key={x}><Check/>{x}</li>)}</ul><Link className="vf-button" href={href("/contact")}>Request a Free Consultation</Link></div></section><Cta/></>; return <><Hero eyebrow="Services" title="Personalized guidance for real-life progress" description="Choose focused support for strength, mobility, nutrition and consistent habits—online or with Chicago sessions available by request."/><section className="vf-section"><div className="vf-wrap"><ServiceCards /></div></section><Cta/></>; }
function About() { return <><Hero eyebrow="MEET YOUR COACH" title="About Angela Williams" description="Personalized support for strength, mobility, confidence and realistic habits."/><section className="vf-section"><div className="vf-wrap vf-about"><div className="vf-portrait"><b>AW</b><small>Customer-approved headshot needed</small></div><div><h2>A welcoming, practical approach</h2><p>Angela Williams is the founder of 360 Vitality Fitness LLC, an online fitness and wellness business serving Chicago-area and online clients. Her approach focuses on helping busy adults develop strength, mobility, confidence and realistic habits through personalized support.</p><aside><b>Customer confirmation needed:</b> professional headshot, certifications, training background, personal fitness story and expanded coaching philosophy. These details are intentionally not invented.</aside><Link className="vf-button" href={href("/contact")}>Request a Free Consultation</Link></div></div></section></>; }
function Contact({ site }: { site: CustomerSite }) { return <><Hero eyebrow="START WITH A CONVERSATION" title="Request a Free Consultation" description="Tell us what you want to improve, and we’ll help you identify a practical place to begin."/><section className="vf-section"><div className="vf-wrap vf-contact"><aside><h2>Contact 360 Vitality Fitness LLC</h2><a href="tel:+18776967333"><b>Phone</b><br/>(877) 696-7333</a><a href="mailto:get360vitalityfitness@gmail.com"><b>Email</b><br/>get360vitalityfitness@gmail.com</a><p><b>Mailing / business address</b><br/>332 S Michigan Ave, Suite 121-5377<br/>Chicago, IL 60604</p><p>Online coaching is available. Chicago-area in-person sessions may be available by appointment or request.</p></aside><div><h2>Tell us about your goals</h2><CustomerContactForm accent="#35a853" customerSlug={site.slug}/></div></div></section><section className="vf-section vf-white"><div className="vf-wrap vf-narrow"><h2>Common questions</h2>{[["Do you offer online coaching?","Yes. Online coaching is available for clients who want flexible, personalized support around their schedules."],["Can I train with you in Chicago?","Chicago-area in-person sessions may be available by request and confirmed appointment."],["Are consultations available without set hours?","Consultations and coaching sessions are available by appointment. Exact operating hours are still being confirmed."]].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section></>; }
function Blog({ slug }: { slug?: string }) { const article = slug ? getArticle(slug) : undefined; if (slug && !article) return <Hero eyebrow="Resources" title="Article not found" description="Browse all published wellness articles."/>; if (article) return <main><section className="vf-article-head"><div className="vf-wrap"><Link href={href("/blog")}>← Blog</Link><p>{article.category}</p><h1>{article.title}</h1><span>By Angela Williams · {article.publishedAt}</span></div></section><figure className="vf-article-image"><Image src={blogImage(article.image)} alt={article.imageAlt} width={1536} height={1024}/><figcaption>{article.imageCaption}</figcaption></figure><article className="vf-wrap vf-article">{article.introduction.map(p=><p key={p}>{p}</p>)}{article.sections.map(section=><section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}{section.bullets&&<ul>{section.bullets.map(x=><li key={x}>{x}</li>)}</ul>}</section>)}<section><h2>Common questions</h2>{article.faq.map(x=><details key={x.question}><summary>{x.question}</summary><p>{x.answer}</p></details>)}</section></article></main>; return <><Hero eyebrow="RESOURCES" title="Practical wellness guidance" description="Approachable ideas for moving more, building strength and creating sustainable habits."/><section className="vf-section"><div className="vf-wrap"><nav className="vf-categories"><Link href={href("/blog")}>All articles</Link>{blogCategories.map(x=><span key={x}>{x}</span>)}</nav><div className="vf-blog-grid">{blogArticles.map(article=><article key={article.slug}><Link href={href(`/blog/${article.slug}`)}><Image src={blogImage(article.image)} alt={article.imageAlt} width={1536} height={1024}/></Link><small>{article.category}</small><h2><Link href={href(`/blog/${article.slug}`)}>{article.title}</Link></h2><p>{article.excerpt}</p><Link href={href(`/blog/${article.slug}`)}>Read article <ArrowRight/></Link></article>)}</div></div></section></>; }
function Legal({ type }: { type: string }) { const content = type === "health-and-fitness-disclaimer" ? ["This website provides general fitness and wellness education, not medical advice, diagnosis or treatment.", "Stop activity and seek appropriate professional guidance for pain, injury, concerning symptoms or medical questions."] : type === "terms-and-conditions" ? ["Consultations and coaching sessions are available by appointment. Services, schedules and availability are confirmed directly with 360 Vitality Fitness LLC.", "This preview retains original customer content and requires business approval before launch."] : ["This starter policy must be reviewed and approved before launch.", "When you submit an inquiry, the website may collect the contact and service information you choose to provide. The current form is in internal test mode and does not send customer delivery.", "Questions may be sent to get360vitalityfitness@gmail.com or (877) 696-7333."]; return <><Hero eyebrow="LEGAL" title={type === "privacy" ? "Privacy Policy" : type === "terms-and-conditions" ? "Terms and Conditions" : "Health & Fitness Disclaimer"} description="Content retained for customer and legal review."/><article className="vf-wrap vf-legal">{content.map(x=><p key={x}>{x}</p>)}</article></>; }
export function VitalityWebsite({ site, route }: { site: CustomerSite; route: string[] }) { const [first, second] = route; const body = !first ? <Home/> : first === "services" ? <Services/> : first === "about" ? <About/> : first === "contact" ? <Contact site={site}/> : first === "blog" ? <Blog slug={second}/> : ["online-fitness-coaching", "personal-training", "nutrition-coaching", "body-assessment", "21-day-fitness-challenge"].includes(first) ? <Services slug={first}/> : ["privacy", "privacy-policy", "terms-and-conditions", "health-and-fitness-disclaimer"].includes(first) ? <Legal type={first === "privacy-policy" ? "privacy" : first}/> : <Home/>; return <div className="vf-site"><Header/>{body}<Footer/>{site.myndy.embed.enabled && <CustomerMyndy agentId={site.myndy.embed.agentId} accent="#148c8c" label="Open the 360 Vitality Fitness AI conversation assistant"/>}</div>; }
