import Image from "next/image";
import Link from "next/link";
import type { Design } from "../catalog";
import "../v2.css";
import "./template.css";

const copy: Record<Design["template"], { headline: string; intro: string; services: string[] }> = {
  forge: { headline: "Spaces with purpose. Places with soul.", intro: "Thoughtful architecture for the way you live and work.", services: ["Residential design", "Commercial spaces", "Project consultation"] },
  ledger: { headline: "Clarity for your next big decision.", intro: "A considered approach to the business you are building.", services: ["Business advisory", "Financial planning", "Strategic guidance"] },
  stillwater: { headline: "A little space to feel more yourself.", intro: "Care, balance, and a thoughtful path to feeling well.", services: ["Personal consultations", "Wellness programs", "Ongoing support"] },
  beacon: { headline: "Your next move. Handled with care.", intro: "Reliable logistics starts with a clear plan.", services: ["Regional transport", "Supply coordination", "Delivery planning"] },
  meridian: { headline: "Made slowly. Shared generously.", intro: "A storefront direction for a neighborhood bakery.", services: ["Artisan bread", "Seasonal pastries", "Community gatherings"] },
  ironwood: { headline: "A place to build your next chapter.", intro: "Custom homes designed around the life you want to live.", services: ["Custom home design", "Renovation planning", "Build coordination"] },
};

export function V2Template({ design, section }: { design: Design; section: "home" | "services" | "about" | "work" | "contact" }) {
  const base = `/templates/${design.template}`;
  const details = copy[design.template];
  return <div className={`v2-template v2-template-${design.template}`}><div className="v2-template-banner"><span>RS WEBFACTORY · {design.ready ? "INTERACTIVE DESIGN EXAMPLE" : "DRAFT DESIGN DIRECTION"}</span><Link href={`/designs/${design.slug}`}>Back to design ↗</Link></div><header><Link className="v2-template-brand" href={base}>{design.name}<small>{design.sector}</small></Link><nav aria-label="Example navigation">{(["home", "services", "about", "work", "contact"] as const).map((page) => <Link key={page} href={page === "home" ? base : `${base}/${page}`} aria-current={page === section ? "page" : undefined}>{page === "work" ? "Our work" : page[0].toUpperCase() + page.slice(1)}</Link>)}</nav></header><main>
    {section === "home" && <><section className="v2-template-hero"><div><small>{design.sector.toUpperCase()} / A NEW PERSPECTIVE</small><h1>{details.headline}</h1><p>{details.intro}</p><Link href={`${base}/services`} className="v2-template-button">Explore services ↗</Link></div><div className="v2-template-photo"><Image src={`/v2/designs/design-${design.image}.jpg`} width={1100} height={760} alt={`${design.name} sample visual`} /><span>Sample visual direction, made for review</span></div></section><section className="v2-template-section"><small>01 / WHAT WE DO</small><h2>A thoughtful approach. A better experience.</h2><div className="v2-template-services">{details.services.map((service, index) => <Link key={service} href={`${base}/services`}><span>0{index + 1}</span><h3>{service}</h3><p>Discover an approach built around your needs.</p><b>↗</b></Link>)}</div></section></>}
    {section === "services" && <section className="v2-template-section"><small>OUR SERVICES</small><h1>Clear expertise. Thoughtful delivery.</h1><p>Three ways to help you take the next step.</p><div className="v2-template-services">{details.services.map((service, index) => <article key={service}><span>0{index + 1}</span><h2>{service}</h2><p>We begin with your goals and agree on a clear scope before moving forward.</p><Link href={`${base}/contact`}>Discuss this direction ↗</Link></article>)}</div></section>}
    {section === "about" && <section className="v2-template-section v2-template-split"><div><small>THE WAY WE WORK</small><h1>Good work begins with understanding.</h1><p>{details.intro}</p><p>This is sample content for a visual direction. Real business claims require customer approval.</p><Link href={`${base}/contact`} className="v2-template-button">Get in touch ↗</Link></div><Image src={`/v2/designs/design-${design.image}.jpg`} width={800} height={600} alt={`${design.name} sample direction`} /></section>}
    {section === "work" && <section className="v2-template-section"><small>OUR WORK</small><h1>A closer look at the possibilities.</h1><p>Concept imagery for this website direction. These are not claims about completed customer projects.</p><div className="v2-template-work"><Image src={`/v2/designs/design-${design.image}.jpg`} width={1100} height={680} alt={`${design.name} concept showcase`} /><h2>{design.name}</h2></div></section>}
    {section === "contact" && <section className="v2-template-section v2-template-split"><div><small>LET’S TALK</small><h1>Every great project starts somewhere.</h1><p>Tell us what you have in mind through the real WebFactory request form.</p><p>This example does not collect or send personal information.</p></div><div className="v2-template-contact"><h2>Start a website request</h2><p>The form opens securely within the WebFactory application.</p><Link className="v2-template-button" href={`/request?design=${encodeURIComponent(design.name)}`}>Open request form ↗</Link></div></section>}
  </main><footer><strong>{design.name}</strong><span>Sample website concept by Red Spectrum WebFactory</span><Link href={`/request?design=${encodeURIComponent(design.name)}`}>Request this direction ↗</Link></footer></div>;
}
